package cbs.dsl.api

/**
 * Service Provider Interface for generated implementation registrations.
 *
 * Implementations are generated by the KSP annotation processor and loaded via
 * [java.util.ServiceLoader] at application startup to register DSL components
 * without runtime classpath scanning.
 *
 * Each implementation should register its DSL definitions into the provided [WritableRegistry].
 * The [WritableRegistry] interface is used instead of the concrete [cbs.dsl.impl.ImplRegistry]
 * to avoid circular dependencies between modules.
 */
interface ImplRegistrationProvider {
  /**
   * Register DSL definitions into the provided registry.
   *
   * @param registry the writable registry to populate with DSL definitions
   */
  fun register(registry: WritableRegistry)
}
