package cbs.nova.starter.capture;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import cbs.nova.starter.core.recorder.ExternalCallRecorder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InOrder;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Pure-unit tests for {@link RecordingStatement}. Uses a Mockito-mocked delegate and a mocked
 * {@link ExternalCallRecorder} so the decorator is exercised without any DB or Spring context.
 */
class RecordingStatementTest {

  private static final String TARGET = "jdbc:h2:mem:test";
  private static final String SQL_SELECT = "select id from orders where id = 1";
  private static final String SQL_INSERT = "insert into orders (name) values ('x')";
  private static final String SQL_UPDATE = "update orders set status = 'done'";
  private static final String SQL_DELETE = "delete from orders where id = 1";

  private ExternalCallRecorder externalCallRecorder;
  private Statement delegate;

  @BeforeEach
  void setUp() {
    externalCallRecorder = mock(ExternalCallRecorder.class);
    delegate = mock(Statement.class);
  }

  private Statement newStatement(String sql) {
    return new RecordingStatement(delegate, sql, TARGET, externalCallRecorder);
  }

  @Test
  void executeQueryForwardsAndRecordsWithFactorySql() throws SQLException {
    ResultSet rs = mock(ResultSet.class);
    when(delegate.executeQuery(SQL_SELECT)).thenReturn(rs);

    Statement statement = newStatement(SQL_SELECT);
    ResultSet actual = statement.executeQuery(SQL_SELECT);

    assertThat(actual).isSameAs(rs);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "SELECT",
            SQL_SELECT);
    verify(delegate).executeQuery(SQL_SELECT);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeUpdateForwardsAndRecordsWithFactorySql() throws SQLException {
    when(delegate.executeUpdate(SQL_UPDATE)).thenReturn(7);

    Statement statement = newStatement(SQL_UPDATE);
    int updated = statement.executeUpdate(SQL_UPDATE);

    assertThat(updated).isEqualTo(7);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "UPDATE",
            SQL_UPDATE);
    verify(delegate).executeUpdate(SQL_UPDATE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeUpdateWithAutoGeneratedKeysForwardsAndRecords() throws SQLException {
    when(delegate.executeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS)).thenReturn(1);

    Statement statement = newStatement(SQL_INSERT);
    int updated = statement.executeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);

    assertThat(updated).isEqualTo(1);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeUpdateWithColumnIndexesForwardsAndRecords() throws SQLException {
    int[] keys = {1};
    when(delegate.executeUpdate(SQL_INSERT, keys)).thenReturn(1);

    Statement statement = newStatement(SQL_INSERT);
    int updated = statement.executeUpdate(SQL_INSERT, keys);

    assertThat(updated).isEqualTo(1);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeUpdate(SQL_INSERT, keys);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeUpdateWithColumnNamesForwardsAndRecords() throws SQLException {
    String[] columns = {"id"};
    when(delegate.executeUpdate(SQL_INSERT, columns)).thenReturn(1);

    Statement statement = newStatement(SQL_INSERT);
    int updated = statement.executeUpdate(SQL_INSERT, columns);

    assertThat(updated).isEqualTo(1);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeUpdate(SQL_INSERT, columns);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeForwardsAndRecordsWithFactorySql() throws SQLException {
    when(delegate.execute(SQL_DELETE)).thenReturn(false);

    Statement statement = newStatement(SQL_DELETE);
    boolean executed = statement.execute(SQL_DELETE);

    assertThat(executed).isFalse();
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "DELETE",
            SQL_DELETE);
    verify(delegate).execute(SQL_DELETE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeWithAutoGeneratedKeysForwardsAndRecords() throws SQLException {
    when(delegate.execute(SQL_INSERT, Statement.RETURN_GENERATED_KEYS)).thenReturn(true);

    Statement statement = newStatement(SQL_INSERT);
    boolean executed = statement.execute(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);

    assertThat(executed).isTrue();
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).execute(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeWithColumnIndexesForwardsAndRecords() throws SQLException {
    int[] keys = {1};
    when(delegate.execute(SQL_INSERT, keys)).thenReturn(true);

    Statement statement = newStatement(SQL_INSERT);
    boolean executed = statement.execute(SQL_INSERT, keys);

    assertThat(executed).isTrue();
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).execute(SQL_INSERT, keys);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeWithColumnNamesForwardsAndRecords() throws SQLException {
    String[] columns = {"id"};
    when(delegate.execute(SQL_INSERT, columns)).thenReturn(true);

    Statement statement = newStatement(SQL_INSERT);
    boolean executed = statement.execute(SQL_INSERT, columns);

    assertThat(executed).isTrue();
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).execute(SQL_INSERT, columns);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeBatchForwardsAndRecordsBatchOperation() throws SQLException {
    int[] counts = {1, 2};
    when(delegate.executeBatch()).thenReturn(counts);

    Statement statement = newStatement(SQL_SELECT);
    int[] actual = statement.executeBatch();

    assertThat(actual).isSameAs(counts);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "BATCH",
            SQL_SELECT);
    verify(delegate).executeBatch();
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeLargeUpdateForwardsAndRecordsWithFactorySql() throws SQLException {
    when(delegate.executeLargeUpdate(SQL_UPDATE)).thenReturn(42L);

    Statement statement = newStatement(SQL_UPDATE);
    long updated = statement.executeLargeUpdate(SQL_UPDATE);

    assertThat(updated).isEqualTo(42L);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "UPDATE",
            SQL_UPDATE);
    verify(delegate).executeLargeUpdate(SQL_UPDATE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeLargeUpdateWithAutoGeneratedKeysForwardsAndRecords() throws SQLException {
    when(delegate.executeLargeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS)).thenReturn(1L);

    Statement statement = newStatement(SQL_INSERT);
    long updated = statement.executeLargeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);

    assertThat(updated).isEqualTo(1L);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeLargeUpdate(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeLargeUpdateWithColumnIndexesForwardsAndRecords() throws SQLException {
    int[] keys = {1};
    when(delegate.executeLargeUpdate(SQL_INSERT, keys)).thenReturn(1L);

    Statement statement = newStatement(SQL_INSERT);
    long updated = statement.executeLargeUpdate(SQL_INSERT, keys);

    assertThat(updated).isEqualTo(1L);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeLargeUpdate(SQL_INSERT, keys);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeLargeUpdateWithColumnNamesForwardsAndRecords() throws SQLException {
    String[] columns = {"id"};
    when(delegate.executeLargeUpdate(SQL_INSERT, columns)).thenReturn(1L);

    Statement statement = newStatement(SQL_INSERT);
    long updated = statement.executeLargeUpdate(SQL_INSERT, columns);

    assertThat(updated).isEqualTo(1L);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            SQL_INSERT);
    verify(delegate).executeLargeUpdate(SQL_INSERT, columns);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void executeLargeBatchForwardsAndRecordsBatchOperation() throws SQLException {
    long[] counts = {10L, 20L};
    when(delegate.executeLargeBatch()).thenReturn(counts);

    Statement statement = newStatement(SQL_SELECT);
    long[] actual = statement.executeLargeBatch();

    assertThat(actual).isSameAs(counts);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "BATCH",
            SQL_SELECT);
    verify(delegate).executeLargeBatch();
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void operationIsFirstUppercaseSqlToken() throws SQLException {
    when(delegate.execute(SQL_INSERT)).thenReturn(false);
    String mixedCaseSql = "  \tInsert Into foo values (1)";

    Statement statement = newStatement(mixedCaseSql);
    statement.execute(mixedCaseSql);

    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "INSERT",
            mixedCaseSql);
    verify(delegate).execute(mixedCaseSql);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void rawStatementExecuteUsesArgumentSql() throws SQLException {
    when(delegate.execute(SQL_DELETE)).thenReturn(false);

    Statement statement = newStatement(null);
    boolean executed = statement.execute(SQL_DELETE);

    assertThat(executed).isFalse();
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "DELETE",
            SQL_DELETE);
    verify(delegate).execute(SQL_DELETE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void factorySqlTakesPrecedenceOverArgumentSql() throws SQLException {
    String argSql = "select 1 from dual";
    when(delegate.executeUpdate(argSql)).thenReturn(3);

    Statement statement = newStatement(SQL_SELECT);
    int updated = statement.executeUpdate(argSql);

    assertThat(updated).isEqualTo(3);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "SELECT",
            SQL_SELECT);
    verify(delegate).executeUpdate(argSql);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void unknownSqlTokenIsUsedWhenSqlMissing() throws SQLException {
    ResultSet rs = mock(ResultSet.class);
    when(delegate.executeQuery(null)).thenReturn(rs);

    Statement statement = newStatement(null);
    statement.executeQuery(null);

    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "UNKNOWN",
            null);
    verify(delegate).executeQuery(null);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void emptySqlFallsBackToUnknownOperation() throws SQLException {
    ResultSet rs = mock(ResultSet.class);
    when(delegate.executeQuery("   ")).thenReturn(rs);

    Statement statement = newStatement("   ");
    statement.executeQuery("   ");

    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "UNKNOWN",
            "   ");
    verify(delegate).executeQuery("   ");
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void nonRecordedMethodsForwardAndDoNotTouchRecorder() throws SQLException {
    Statement statement = newStatement(SQL_SELECT);
    statement.setFetchSize(100);
    statement.close();

    verify(delegate).setFetchSize(100);
    verify(delegate).close();
    verifyNoInteractions(externalCallRecorder);
  }

  @Test
  void getterMethodsForwardAndDoNotTouchRecorder() throws SQLException {
    when(delegate.getResultSet()).thenReturn(mock(ResultSet.class));
    when(delegate.getUpdateCount()).thenReturn(11);
    when(delegate.getFetchSize()).thenReturn(50);
    when(delegate.isClosed()).thenReturn(false);

    Statement statement = newStatement(SQL_SELECT);
    ResultSet rs = statement.getResultSet();
    int count = statement.getUpdateCount();
    int fetchSize = statement.getFetchSize();
    boolean closed = statement.isClosed();

    assertThat(rs).isNotNull();
    assertThat(count).isEqualTo(11);
    assertThat(fetchSize).isEqualTo(50);
    assertThat(closed).isFalse();
    verify(delegate).getResultSet();
    verify(delegate).getUpdateCount();
    verify(delegate).getFetchSize();
    verify(delegate).isClosed();
    verifyNoInteractions(externalCallRecorder);
  }

  @Test
  void recordHappensBeforeDelegateInvocation() throws SQLException {
    when(delegate.executeUpdate(SQL_UPDATE)).thenReturn(1);

    Statement statement = newStatement(SQL_UPDATE);
    statement.executeUpdate(SQL_UPDATE);

    InOrder ordered = inOrder(externalCallRecorder, delegate);
    ordered.verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET,
            "UPDATE", SQL_UPDATE);
    ordered.verify(delegate).executeUpdate(SQL_UPDATE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void delegateFailureStillRecordsAndSurfacesOriginalCause() throws SQLException {
    SQLException cause = new SQLException("boom");
    when(delegate.executeUpdate(SQL_UPDATE)).thenThrow(cause);

    Statement statement = newStatement(SQL_UPDATE);
    assertThatThrownBy(() -> statement.executeUpdate(SQL_UPDATE))
            .isSameAs(cause);

    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "UPDATE",
            SQL_UPDATE);
    verify(delegate, times(1)).executeUpdate(SQL_UPDATE);
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void delegateFailureOnBatchStillRecordsBatchOperation() throws SQLException {
    SQLException cause = new SQLException("batch-fail");
    when(delegate.executeBatch()).thenThrow(cause);

    Statement statement = newStatement(SQL_SELECT);
    assertThatThrownBy(statement::executeBatch)
            .isSameAs(cause);

    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "BATCH",
            SQL_SELECT);
    verify(delegate).executeBatch();
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void decoratorIdentityMethodsReturnConsistentValues() {
    Statement statement = newStatement(SQL_SELECT);
    Statement otherStatement = newStatement(SQL_SELECT);

    assertThat(statement.equals(statement)).isTrue();
    assertThat(statement.equals(delegate)).isFalse();
    assertThat(statement.equals(otherStatement)).isFalse();
    assertThat(statement.hashCode()).isEqualTo(System.identityHashCode(statement));
    assertThat(statement.toString()).contains("RecordingStatement");
  }

  @Test
  void wrapperMethodsForwardToDelegate() throws SQLException {
    when(delegate.isWrapperFor(Statement.class)).thenReturn(true);
    when(delegate.unwrap(Statement.class)).thenReturn(delegate);

    Statement statement = newStatement(SQL_SELECT);
    boolean wrapper = statement.isWrapperFor(Statement.class);
    Statement unwrapped = statement.unwrap(Statement.class);

    assertThat(wrapper).isTrue();
    assertThat(unwrapped).isSameAs(delegate);
    verify(delegate).isWrapperFor(Statement.class);
    verify(delegate).unwrap(Statement.class);
    verifyNoInteractions(externalCallRecorder);
  }

  @Test
  void rawStatementExecuteBatchRecordsBatchOperation() throws SQLException {
    int[] counts = {2, 3};
    when(delegate.executeBatch()).thenReturn(counts);

    Statement statement = newStatement(null);
    int[] actual = statement.executeBatch();

    assertThat(actual).isSameAs(counts);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "BATCH",
            null);
    verify(delegate).executeBatch();
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }

  @Test
  void rawStatementExecuteLargeBatchRecordsBatchOperation() throws SQLException {
    long[] counts = {5L, 6L};
    when(delegate.executeLargeBatch()).thenReturn(counts);

    Statement statement = newStatement(null);
    long[] actual = statement.executeLargeBatch();

    assertThat(actual).isSameAs(counts);
    verify(externalCallRecorder).record(ExternalCallRecorder.TYPE_DATABASE, TARGET, "BATCH",
            null);
    verify(delegate).executeLargeBatch();
    verifyNoMoreInteractions(externalCallRecorder, delegate);
  }
}
