package cbs.nova.dsl;

public enum PreviewErrorCode {
  DSL_COMPILATION_ERROR, HELPER_NOT_FOUND, EXTERNAL_CALL_FAILED, INPUT_VALIDATION_ERROR, COMPENSATION_ERROR, PREVIEW_TIMEOUT, TIMEOUT_EXCEEDED, UNKNOWN_ERROR
}
