plugins {
  id 'java'
}

group = 'cbs.nova.dsl.sample1'
version = '1.0.0'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation files('libs/dsl-api.jar')
  implementation files('libs/dsl-codegen.jar')
  implementation 'com.palantir.javapoet:javapoet:0.11.0'
}

tasks.register('compileDsl', JavaExec) {
  dependsOn configurations.runtimeClasspath
  classpath = files('libs/dsl-api.jar', 'libs/dsl-codegen.jar') + configurations.runtimeClasspath
  mainClass = 'cbs.dsl.codegen.DslCompiler'
  args '.', 'build/dsl-classes'
  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(25)
  }
}
