plugins {
  id 'java-library'
  alias(libs.plugins.test.logger)
}

dependencies {
  api project(":dsl-api")
  implementation libs.slf4j.api
  implementation libs.javaparser
  implementation libs.jackson.databind3
  testAnnotationProcessor libs.avaje.jsonb.generator
  annotationProcessor libs.avaje.jsonb.generator

  testImplementation platform(libs.junit.bom)
  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testRuntimeOnly libs.junit.platform.launcher
}
