plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dm)
}

group = 'cbs.nova'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation libs.cbs.nova.starter
    implementation libs.cbs.nova.app.dsl

    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.actuator
    runtimeOnly libs.h2

    testImplementation libs.spring.boot.starter.test
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
