rootProject.name = 'cbs-nova-backend'

include 'dsl-api'
include 'dsl'
include 'dsl-codegen'
include 'starter'
include 'temporal-example'
include 'dsl-examples'
include 'dsl-model'

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
  repositories {
    mavenLocal()
    mavenCentral()
  }
}

enableFeaturePreview('TYPESAFE_PROJECT_ACCESSORS')

include 'misc-codegen'