pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
  }
  resolutionStrategy {
    eachPlugin {
      if (requested.id.id == 'cbs.nova.dsl') {
        useModule("cbs.nova:dsl-gradle-plugin:${requested.version ?: version}")
      }
    }
  }
}

rootProject.name = 'cbs-nova-backend'

include 'dsl-api'
include 'dsl'
include 'dsl-codegen'
include 'starter'
include 'starter-example'
include 'dsl-examples'
include 'dsl-model'
include 'dsl-gradle-plugin'
include 'misc-codegen'

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
  repositories {
    mavenLocal()
    mavenCentral()
  }
}

enableFeaturePreview('TYPESAFE_PROJECT_ACCESSORS')
