pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
  }
  resolutionStrategy {
    eachPlugin {
      if (requested.id.id == 'cbs.nova.dsl') {
        useModule("cbs.nova:dsl-gradle-plugin:${requested.version ?: version}")
      }
    }
  }
  plugins {
    id 'org.jetbrains.intellij.platform.settings' version '2.18.1'
  }
}

plugins {
  id 'org.jetbrains.intellij.platform.settings'
}

rootProject.name = 'cbs-nova-backend'

include 'dsl-api'
include 'dsl'
include 'dsl-codegen'
include 'dsl-examples'
include 'dsl-gradle-plugin'
include 'dsl-idea-plugin'
include 'misc-codegen'
include 'starter'

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
  repositories {
    mavenLocal()
    mavenCentral()
    intellijPlatform {
      defaultRepositories()
    }
  }
}

enableFeaturePreview('TYPESAFE_PROJECT_ACCESSORS')
