CREATE TABLE IF NOT EXISTS dsl_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(255) NOT NULL UNIQUE,
    process_name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_json TEXT,
    output_json TEXT,
    error_message TEXT,
    context_json TEXT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    execution_mode VARCHAR(32),
    triggered_by VARCHAR(320),
    correlation_id VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS dsl_run_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(255) NOT NULL,
    transaction_name VARCHAR(255) NOT NULL,
    input_json TEXT,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dsl_run_transactions_run_id ON dsl_run_transactions(run_id);
CREATE INDEX IF NOT EXISTS idx_dsl_run_transactions_status ON dsl_run_transactions(status);

CREATE TABLE IF NOT EXISTS dsl_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor VARCHAR(320) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target VARCHAR(512) NOT NULL,
    correlation_id VARCHAR(200),
    outcome VARCHAR(16) NOT NULL,
    details_json TEXT
);

-- Append-only audit log: rows are inserted by DslAuditRepository and never updated or deleted.
CREATE INDEX IF NOT EXISTS idx_dsl_audit_occurred_at ON dsl_audit (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dsl_audit_action ON dsl_audit (action);

CREATE TABLE IF NOT EXISTS dsl_webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    subscription_id VARCHAR(200) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL,
    last_error VARCHAR(1000),
    duration_ms BIGINT
);

-- Append-only delivery log: rows are inserted by WebhookDeliveryRecordRepository and never updated or deleted.
CREATE INDEX IF NOT EXISTS idx_dsl_webhook_deliveries_subscription_occurred_at ON dsl_webhook_deliveries (subscription_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dsl_webhook_deliveries_occurred_at ON dsl_webhook_deliveries (occurred_at DESC);

CREATE TABLE IF NOT EXISTS dsl_compile_diagnostics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(16) NOT NULL,
    definition VARCHAR(256) NOT NULL,
    file VARCHAR(512),
    line INT,
    col_number INT,
    severity VARCHAR(16) NOT NULL,
    code VARCHAR(64),
    message TEXT NOT NULL
);

-- Append-only compile diagnostic log: rows are inserted by CompileDiagnosticRecordRepository
-- and never updated or deleted.
CREATE INDEX IF NOT EXISTS idx_dsl_compile_diagnostics_occurred_at ON dsl_compile_diagnostics (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dsl_compile_diagnostics_definition_occurred_at ON dsl_compile_diagnostics (definition, occurred_at DESC);

CREATE TABLE IF NOT EXISTS dsl_definition_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_name VARCHAR(200) NOT NULL,
    case_name VARCHAR(200) NOT NULL,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Author-defined example inputs + expected outputs stored per definition; H2 has no JSONB so
-- payloads are kept as TEXT (mirrors dsl_audit.details_json).
CREATE UNIQUE INDEX IF NOT EXISTS uq_dsl_definition_tests_name_case
    ON dsl_definition_tests (definition_name, case_name);
CREATE INDEX IF NOT EXISTS idx_dsl_definition_tests_definition_name
    ON dsl_definition_tests (definition_name);
CREATE TABLE IF NOT EXISTS dsl_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    key_prefix VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    last_used_at TIMESTAMP WITH TIME ZONE NULL
);

-- Stored API keys (T410). key_hash stores the SHA-256 hex digest of the plaintext key;
-- the plaintext is returned exactly once at creation and never persisted. H2 has no
-- partial-index syntax, so revoked_at is indexed plainly; queries always filter on
-- revoked_at IS NULL anyway.
CREATE UNIQUE INDEX IF NOT EXISTS uq_dsl_api_keys_key_hash
    ON dsl_api_keys (key_hash);
CREATE INDEX IF NOT EXISTS idx_dsl_api_keys_revoked_at
    ON dsl_api_keys (revoked_at);

CREATE TABLE IF NOT EXISTS dsl_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id VARCHAR(200) NOT NULL,
    correlation_id VARCHAR(128) NULL,
    payload TEXT NOT NULL,
    schema_version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- T411: append-only domain event store (phase 1: writes + list). H2 has no JSONB so payloads
-- are stored as TEXT, mirroring dsl_definition_tests.input/expected_output and dsl_audit.details_json.
-- Index layout matches the Postgres migration so the JDBC repo is dialect-agnostic.
CREATE INDEX IF NOT EXISTS idx_dsl_events_aggregate
    ON dsl_events (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_dsl_events_correlation_id
    ON dsl_events (correlation_id);
CREATE INDEX IF NOT EXISTS idx_dsl_events_event_type
    ON dsl_events (event_type);
CREATE INDEX IF NOT EXISTS idx_dsl_events_created_at
    ON dsl_events (created_at);
-- T492: run attribution — tie every run to the definition version it executed.
-- definition_hash is DESCRIPTOR identity: sha256 over the Jackson-serialized
-- DslDescriptor (taskQueue / version / timeouts), the same value the preview cache
-- keys on. It is NOT full logic identity — two functionally different definitions
-- with the same descriptor collide. A true content hash computed at publish/reload
-- time is a planned Epic 5 follow-up.
-- Nullable: historical rows and runs whose descriptor cannot be resolved stay NULL.
-- IF NOT EXISTS keeps the script idempotent: h2 test slices re-apply classpath
-- migrations per test method against a shared in-memory database.
ALTER TABLE dsl_runs ADD COLUMN IF NOT EXISTS definition_hash VARCHAR(64);

COMMENT ON COLUMN dsl_runs.definition_hash IS
    'Descriptor-identity sha256 (64-char lowercase hex) of the DslDescriptor the run '
    'executed — NOT full logic identity; true content hash is a follow-up. NULL for '
    'historical rows and runs with an unresolvable definition.';

CREATE TABLE IF NOT EXISTS dsl_notification_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    event_type VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(64),
    aggregate_id_pattern VARCHAR(255),
    definition_pattern VARCHAR(255),
    status VARCHAR(64),
    actions TEXT NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    rate_class VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- T565: notification rules engine. H2 has no JSONB so actions are stored as TEXT,
-- mirroring dsl_events.payload. Index layout matches the Postgres migration so the
-- JDBC repositories stay dialect-agnostic.
CREATE INDEX IF NOT EXISTS idx_dsl_notification_rule_event_type_enabled
    ON dsl_notification_rule (event_type, enabled);

CREATE TABLE IF NOT EXISTS dsl_notification_rule_firing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    sink VARCHAR(32) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    detail VARCHAR(1024),
    duration_ms BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Append-only firing audit: one row per (matched rule, action) per published event.
CREATE INDEX IF NOT EXISTS idx_dsl_notification_rule_firing_rule_id
    ON dsl_notification_rule_firing (rule_id);
CREATE INDEX IF NOT EXISTS idx_dsl_notification_rule_firing_event_id
    ON dsl_notification_rule_firing (event_id);
CREATE INDEX IF NOT EXISTS idx_dsl_notification_rule_firing_created_at
    ON dsl_notification_rule_firing (created_at);

-- T566: track MQ delivery in the existing transactional outbox.
ALTER TABLE dsl_events ADD COLUMN IF NOT EXISTS mq_published BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_dsl_events_mq_published
    ON dsl_events (mq_published);

CREATE TABLE IF NOT EXISTS dsl_change_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_name VARCHAR(255) NOT NULL,
    draft_content TEXT NOT NULL,
    requested_by VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,
    approved_by VARCHAR(255),
    approved_at TIMESTAMP WITH TIME ZONE,
    comment VARCHAR(1024)
);

-- T568: change-request approval gate for DSL publish. The (definition_name, status) index
-- covers both the pending lookup used to supersede prior requests and the filtered list
-- endpoint; H2 has no JSONB so draft_content is stored as TEXT, mirroring
-- dsl_events.payload. Index layout matches the Postgres migration so the JDBC repository
-- stays dialect-agnostic.
CREATE INDEX IF NOT EXISTS idx_dsl_change_request_definition_status
    ON dsl_change_request (definition_name, status);

CREATE INDEX IF NOT EXISTS idx_dsl_change_request_requested_at
    ON dsl_change_request (requested_at);
