CREATE TABLE IF NOT EXISTS dsl_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(255) NOT NULL UNIQUE,
    process_name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_json TEXT,
    output_json TEXT,
    error_message TEXT,
    context_json TEXT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    execution_mode VARCHAR(32),
    triggered_by VARCHAR(320),
    correlation_id VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS dsl_run_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(255) NOT NULL,
    transaction_name VARCHAR(255) NOT NULL,
    input_json TEXT,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dsl_run_transactions_run_id ON dsl_run_transactions(run_id);
CREATE INDEX IF NOT EXISTS idx_dsl_run_transactions_status ON dsl_run_transactions(status);
