CREATE TABLE IF NOT EXISTS dsl_webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    subscription_id VARCHAR(200) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL,
    last_error VARCHAR(1000),
    duration_ms BIGINT
);

-- Append-only delivery log: rows are inserted by WebhookDeliveryRecordRepository and never updated or deleted.
CREATE INDEX IF NOT EXISTS idx_dsl_webhook_deliveries_subscription_occurred_at ON dsl_webhook_deliveries (subscription_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dsl_webhook_deliveries_occurred_at ON dsl_webhook_deliveries (occurred_at DESC);
