CREATE TABLE IF NOT EXISTS dsl_compile_diagnostics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(16) NOT NULL,
    definition VARCHAR(256) NOT NULL,
    file VARCHAR(512),
    line INT,
    col_number INT,
    severity VARCHAR(16) NOT NULL,
    code VARCHAR(64),
    message TEXT NOT NULL
);

-- Append-only compile diagnostic log: rows are inserted by CompileDiagnosticRecordRepository
-- and never updated or deleted.
CREATE INDEX IF NOT EXISTS idx_dsl_compile_diagnostics_occurred_at ON dsl_compile_diagnostics (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dsl_compile_diagnostics_definition_occurred_at ON dsl_compile_diagnostics (definition, occurred_at DESC);
