CREATE TABLE IF NOT EXISTS dsl_definition_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_name VARCHAR(200) NOT NULL,
    case_name VARCHAR(200) NOT NULL,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Author-defined example inputs + expected outputs stored per definition; H2 has no JSONB so
-- payloads are kept as TEXT (mirrors dsl_audit.details_json).
CREATE UNIQUE INDEX IF NOT EXISTS uq_dsl_definition_tests_name_case
    ON dsl_definition_tests (definition_name, case_name);
CREATE INDEX IF NOT EXISTS idx_dsl_definition_tests_definition_name
    ON dsl_definition_tests (definition_name);