CREATE TABLE IF NOT EXISTS dsl_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    key_prefix VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    last_used_at TIMESTAMP WITH TIME ZONE NULL
);

-- Stored API keys (T410). key_hash stores the SHA-256 hex digest of the plaintext key;
-- the plaintext is returned exactly once at creation and never persisted. H2 has no
-- partial-index syntax, so revoked_at is indexed plainly; queries always filter on
-- revoked_at IS NULL anyway.
CREATE UNIQUE INDEX IF NOT EXISTS uq_dsl_api_keys_key_hash
    ON dsl_api_keys (key_hash);
CREATE INDEX IF NOT EXISTS idx_dsl_api_keys_revoked_at
    ON dsl_api_keys (revoked_at);
