apply plugin: 'com.diffplug.spotless'

spotless {
  java {
    eclipse().configFile("${rootDir}/../gradle/eclipse-formatter.xml")

    trimTrailingWhitespace()
    endWithNewline()
    leadingTabsToSpaces(2)

    custom 'Forbid Legacy ObjectMapper', { text ->
      if (text.contains('com.fasterxml.jackson.databind.ObjectMapper')) {
        throw new GradleException("Error: Legacy Jackson 2 ObjectMapper detected! Use 'tools.jackson.databind.ObjectMapper' instead.")
      }
    }
  }
  format('misc') {
    target('*.md', '.gitignore', '*.properties')
    trimTrailingWhitespace()
    endWithNewline()
  }
}
