plugins {
  id 'java'
  alias(libs.plugins.spring.boot)
  alias(libs.plugins.spring.dm)
}

dependencies {
  implementation project(':starter')
  implementation project(':dsl-examples')
  implementation project(':dsl-api')
  implementation project(':dsl')

  implementation libs.temporal.sdk

  testImplementation libs.bundles.spring.test
  testImplementation libs.temporal.testing
  testImplementation libs.testcontainers.core
  testImplementation libs.testcontainers.junit.jupiter
  testImplementation libs.keycloak.admin.client
  testImplementation libs.rest.assured
}

bootJar {
  enabled = false
}

jar {
  enabled = true
}
