plugins {
  id 'java-library'
  alias(libs.plugins.test.logger)
}

dependencies {
  api libs.jspecify
  api libs.avaje.jsonb
  annotationProcessor libs.avaje.jsonb.generator

  testImplementation platform(libs.junit.bom)
  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testRuntimeOnly libs.junit.platform.launcher
}
