package cbs.dsl.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Generates the [GeneratedImplRegistrations] Kotlin object and SPI service file.
 *
 * The generated object implements [cbs.dsl.api.ImplRegistrationProvider] and registers all
 * discovered DSL components into the [cbs.dsl.api.WritableRegistry].
 */
class RegistrationGenerator(private val codeGenerator: CodeGenerator) {

  fun generate(registrations: List<RegistrationSpec>) {
    generateImplRegistrations(registrations)
    generateSpiFile()
  }

  private fun generateSpiFile() {
    val packageName = "META-INF/services"
    val fileName = "cbs.dsl.api.ImplRegistrationProvider"
    codeGenerator.createNewFile(Dependencies.ALL_FILES, packageName, fileName, "").use {
        outputStream ->
      OutputStreamWriter(outputStream, StandardCharsets.UTF_8).use { writer ->
        writer.write("cbs.dsl.codegen.generated.GeneratedImplRegistrations")
      }
    }
  }

  private fun generateImplRegistrations(registrations: List<RegistrationSpec>) {
    val packageName = "cbs.dsl.codegen.generated"
    val fileName = "GeneratedImplRegistrations"

    codeGenerator.createNewFile(Dependencies.ALL_FILES, packageName, fileName).use { outputStream ->
      OutputStreamWriter(outputStream, StandardCharsets.UTF_8).use { writer ->
        writer.appendLine("package $packageName")
        writer.appendLine()
        writer.appendLine("import cbs.dsl.api.ImplRegistrationProvider")
        writer.appendLine("import cbs.dsl.api.WritableRegistry")
        // Add imports for all registered classes
        registrations.forEach { spec ->
          writer.appendLine("import ${spec.packageName}.${spec.className}")
        }
        writer.appendLine()
        writer.appendLine("/**")
        writer.appendLine(" * Generated implementation registrant.")
        writer.appendLine(" * This file is auto-generated by the KSP annotation processor.")
        writer.appendLine(" * Do not edit manually.")
        writer.appendLine(" */")
        writer.appendLine("object GeneratedImplRegistrations : ImplRegistrationProvider {")
        writer.appendLine()
        writer.appendLine("  override fun register(registry: WritableRegistry) {")

        if (registrations.isEmpty()) {
          writer.appendLine("    // No DSL components to register")
        } else {
          registrations.forEach { spec ->
            writer.appendLine("    registry.register(${spec.className}())")
          }
        }

        writer.appendLine("  }")
        writer.appendLine("}")
      }
    }
  }
}
