plugins {
  id 'java-library'
  id 'maven-publish'
}

dependencies {
  implementation project(":dsl-api")

  testImplementation platform(libs.junit.bom)
  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testImplementation libs.slf4j.api
  testRuntimeOnly libs.junit.platform.launcher
}