package cbs.nova.starter.capture;

import cbs.nova.starter.core.recorder.ExternalCallRecorder;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.ShardingKey;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Typed decorator around a real {@link Connection}. Statement factory methods wrap the returned
 * statements in {@link RecordingStatement} / {@link RecordingPreparedStatement} /
 * {@link RecordingCallableStatement}; every other method delegates directly. The recording target
 * (the JDBC URL, or {@link #FALLBACK_TARGET}) is resolved once per connection.
 */
public class RecordingConnection implements Connection {

  public static final String FALLBACK_TARGET = "jdbc:datasource";

  private final Connection delegate;
  private final ExternalCallRecorder externalCallRecorder;
  private @Nullable String target;

  public RecordingConnection(@NonNull Connection delegate,
          @NonNull ExternalCallRecorder externalCallRecorder) {
    this.delegate = delegate;
    this.externalCallRecorder = externalCallRecorder;
  }

  @Override
  public Statement createStatement() throws SQLException {
    Statement statement = delegate.createStatement();
    return statement == null ? null : wrapStatement(statement, null);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency)
          throws SQLException {
    Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency);
    return statement == null ? null : wrapStatement(statement, null);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency,
          int resultSetHoldability) throws SQLException {
    Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency,
            resultSetHoldability);
    return statement == null ? null : wrapStatement(statement, null);
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
          throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, autoGeneratedKeys);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, columnIndexes);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, columnNames);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType,
          int resultSetConcurrency) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, resultSetType,
            resultSetConcurrency);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType,
          int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, resultSetType,
            resultSetConcurrency, resultSetHoldability);
    return statement == null
            ? null
            : new RecordingPreparedStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    CallableStatement statement = delegate.prepareCall(sql);
    return statement == null
            ? null
            : new RecordingCallableStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
          throws SQLException {
    CallableStatement statement = delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
    return statement == null
            ? null
            : new RecordingCallableStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
          int resultSetHoldability) throws SQLException {
    CallableStatement statement = delegate.prepareCall(sql, resultSetType, resultSetConcurrency,
            resultSetHoldability);
    return statement == null
            ? null
            : new RecordingCallableStatement(statement, sql, target(),
                    externalCallRecorder);
  }

  private Statement wrapStatement(@NonNull Statement statement, @Nullable String sql) {
    if (statement instanceof CallableStatement callableStatement) {
      return new RecordingCallableStatement(callableStatement, sql, target(),
              externalCallRecorder);
    }
    if (statement instanceof PreparedStatement preparedStatement) {
      return new RecordingPreparedStatement(preparedStatement, sql, target(),
              externalCallRecorder);
    }
    return new RecordingStatement(statement, sql, target(), externalCallRecorder);
  }

  private @NonNull String target() {
    if (target == null) {
      target = resolveTarget();
    }
    return target;
  }

  private @NonNull String resolveTarget() {
    try {
      String url = delegate.getMetaData().getURL();
      if (url != null && !url.isBlank()) {
        return url;
      }
    } catch (SQLException ignored) {
      // fall through to fallback
    }
    return FALLBACK_TARGET;
  }

  @Override
  public String nativeSQL(String sql) throws SQLException {
    return delegate.nativeSQL(sql);
  }

  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    delegate.setAutoCommit(autoCommit);
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    return delegate.getAutoCommit();
  }

  @Override
  public void commit() throws SQLException {
    delegate.commit();
  }

  @Override
  public void rollback() throws SQLException {
    delegate.rollback();
  }

  @Override
  public void rollback(Savepoint savepoint) throws SQLException {
    delegate.rollback(savepoint);
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return delegate.isClosed();
  }

  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    return delegate.getMetaData();
  }

  @Override
  public void setReadOnly(boolean readOnly) throws SQLException {
    delegate.setReadOnly(readOnly);
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    return delegate.isReadOnly();
  }

  @Override
  public void setCatalog(String catalog) throws SQLException {
    delegate.setCatalog(catalog);
  }

  @Override
  public String getCatalog() throws SQLException {
    return delegate.getCatalog();
  }

  @Override
  public void setTransactionIsolation(int level) throws SQLException {
    delegate.setTransactionIsolation(level);
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    return delegate.getTransactionIsolation();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return delegate.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    delegate.clearWarnings();
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    return delegate.getTypeMap();
  }

  @Override
  public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    delegate.setTypeMap(map);
  }

  @Override
  public void setHoldability(int holdability) throws SQLException {
    delegate.setHoldability(holdability);
  }

  @Override
  public int getHoldability() throws SQLException {
    return delegate.getHoldability();
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    return delegate.setSavepoint();
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    return delegate.setSavepoint(name);
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    delegate.releaseSavepoint(savepoint);
  }

  @Override
  public void setClientInfo(String name, String value) throws SQLClientInfoException {
    delegate.setClientInfo(name, value);
  }

  @Override
  public void setClientInfo(Properties properties) throws SQLClientInfoException {
    delegate.setClientInfo(properties);
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    return delegate.getClientInfo();
  }

  @Override
  public String getClientInfo(String name) throws SQLException {
    return delegate.getClientInfo(name);
  }

  @Override
  public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    return delegate.createArrayOf(typeName, elements);
  }

  @Override
  public Blob createBlob() throws SQLException {
    return delegate.createBlob();
  }

  @Override
  public Clob createClob() throws SQLException {
    return delegate.createClob();
  }

  @Override
  public NClob createNClob() throws SQLException {
    return delegate.createNClob();
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    return delegate.createSQLXML();
  }

  @Override
  public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    return delegate.createStruct(typeName, attributes);
  }

  @Override
  public void setSchema(String schema) throws SQLException {
    delegate.setSchema(schema);
  }

  @Override
  public String getSchema() throws SQLException {
    return delegate.getSchema();
  }

  @Override
  public void abort(Executor executor) throws SQLException {
    delegate.abort(executor);
  }

  @Override
  public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    delegate.setNetworkTimeout(executor, milliseconds);
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    return delegate.getNetworkTimeout();
  }

  @Override
  public void beginRequest() throws SQLException {
    delegate.beginRequest();
  }

  @Override
  public void endRequest() throws SQLException {
    delegate.endRequest();
  }

  @Override
  public boolean setShardingKeyIfValid(ShardingKey shardingKey, int timeout)
          throws SQLException {
    return delegate.setShardingKeyIfValid(shardingKey, timeout);
  }

  @Override
  public boolean setShardingKeyIfValid(ShardingKey superShardingKey, ShardingKey shardingKey,
          int timeout) throws SQLException {
    return delegate.setShardingKeyIfValid(superShardingKey, shardingKey, timeout);
  }

  @Override
  public void setShardingKey(ShardingKey shardingKey) throws SQLException {
    delegate.setShardingKey(shardingKey);
  }

  @Override
  public void setShardingKey(ShardingKey superShardingKey, ShardingKey shardingKey)
          throws SQLException {
    delegate.setShardingKey(superShardingKey, shardingKey);
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    return delegate.unwrap(iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return delegate.isWrapperFor(iface);
  }

  @Override
  public boolean isValid(int timeout) throws SQLException {
    return delegate.isValid(timeout);
  }

  @Override
  public boolean equals(Object obj) {
    return this == obj;
  }

  @Override
  public int hashCode() {
    return System.identityHashCode(this);
  }

  @Override
  public String toString() {
    return "RecordingConnection[" + delegate + "]";
  }
}
