package cbs.nova.starter.capture;

import cbs.nova.starter.core.recorder.ExternalCallRecorder;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Typed decorator around a real {@link Statement}. Every method delegates with a compile-time-typed
 * call; the {@code execute*} methods additionally record the call via the
 * {@link ExternalCallRecorder} before delegating, using the factory SQL when present and the
 * argument SQL otherwise. Batch execution records the {@code BATCH} operation.
 */
public class RecordingStatement implements Statement {

  private static final String OPERATION_BATCH = "BATCH";

  private final Statement delegate;
  private final @Nullable String sql;
  private final String target;
  private final ExternalCallRecorder externalCallRecorder;

  public RecordingStatement(@NonNull Statement delegate, @Nullable String sql,
          @NonNull String target, @NonNull ExternalCallRecorder externalCallRecorder) {
    this.delegate = delegate;
    this.sql = sql;
    this.target = target;
    this.externalCallRecorder = externalCallRecorder;
  }

  @Override
  public ResultSet executeQuery(String argumentSql) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeQuery(argumentSql);
  }

  @Override
  public int executeUpdate(String argumentSql) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeUpdate(argumentSql);
  }

  @Override
  public int executeUpdate(String argumentSql, int autoGeneratedKeys) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeUpdate(argumentSql, autoGeneratedKeys);
  }

  @Override
  public int executeUpdate(String argumentSql, int[] columnIndexes) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeUpdate(argumentSql, columnIndexes);
  }

  @Override
  public int executeUpdate(String argumentSql, String[] columnNames) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeUpdate(argumentSql, columnNames);
  }

  @Override
  public boolean execute(String argumentSql) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.execute(argumentSql);
  }

  @Override
  public boolean execute(String argumentSql, int autoGeneratedKeys) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.execute(argumentSql, autoGeneratedKeys);
  }

  @Override
  public boolean execute(String argumentSql, int[] columnIndexes) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.execute(argumentSql, columnIndexes);
  }

  @Override
  public boolean execute(String argumentSql, String[] columnNames) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.execute(argumentSql, columnNames);
  }

  @Override
  public int[] executeBatch() throws SQLException {
    recordBatch();
    return delegate.executeBatch();
  }

  @Override
  public long executeLargeUpdate(String argumentSql) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeLargeUpdate(argumentSql);
  }

  @Override
  public long executeLargeUpdate(String argumentSql, int autoGeneratedKeys) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeLargeUpdate(argumentSql, autoGeneratedKeys);
  }

  @Override
  public long executeLargeUpdate(String argumentSql, int[] columnIndexes) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeLargeUpdate(argumentSql, columnIndexes);
  }

  @Override
  public long executeLargeUpdate(String argumentSql, String[] columnNames) throws SQLException {
    recordCall(effectiveSql(argumentSql));
    return delegate.executeLargeUpdate(argumentSql, columnNames);
  }

  @Override
  public long[] executeLargeBatch() throws SQLException {
    recordBatch();
    return delegate.executeLargeBatch();
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return delegate.getMaxFieldSize();
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    delegate.setMaxFieldSize(max);
  }

  @Override
  public int getMaxRows() throws SQLException {
    return delegate.getMaxRows();
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    delegate.setMaxRows(max);
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    delegate.setEscapeProcessing(enable);
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return delegate.getQueryTimeout();
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    delegate.setQueryTimeout(seconds);
  }

  @Override
  public void cancel() throws SQLException {
    delegate.cancel();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return delegate.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    delegate.clearWarnings();
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    delegate.setCursorName(name);
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    return delegate.getResultSet();
  }

  @Override
  public int getUpdateCount() throws SQLException {
    return delegate.getUpdateCount();
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    return delegate.getMoreResults();
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    return delegate.getMoreResults(current);
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    delegate.setFetchDirection(direction);
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return delegate.getFetchDirection();
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    delegate.setFetchSize(rows);
  }

  @Override
  public int getFetchSize() throws SQLException {
    return delegate.getFetchSize();
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return delegate.getResultSetConcurrency();
  }

  @Override
  public int getResultSetType() throws SQLException {
    return delegate.getResultSetType();
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    delegate.addBatch(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    delegate.clearBatch();
  }

  @Override
  public Connection getConnection() throws SQLException {
    return delegate.getConnection();
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    return delegate.getGeneratedKeys();
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return delegate.getResultSetHoldability();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return delegate.isClosed();
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    delegate.setPoolable(poolable);
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return delegate.isPoolable();
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    delegate.closeOnCompletion();
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return delegate.isCloseOnCompletion();
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    return delegate.unwrap(iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return delegate.isWrapperFor(iface);
  }

  @Override
  public long getLargeUpdateCount() throws SQLException {
    return delegate.getLargeUpdateCount();
  }

  @Override
  public long getLargeMaxRows() throws SQLException {
    return delegate.getLargeMaxRows();
  }

  @Override
  public void setLargeMaxRows(long max) throws SQLException {
    delegate.setLargeMaxRows(max);
  }

  @Override
  public String enquoteLiteral(String val) throws SQLException {
    return delegate.enquoteLiteral(val);
  }

  @Override
  public String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException {
    return delegate.enquoteIdentifier(identifier, alwaysQuote);
  }

  @Override
  public boolean isSimpleIdentifier(String identifier) throws SQLException {
    return delegate.isSimpleIdentifier(identifier);
  }

  @Override
  public String enquoteNCharLiteral(String val) throws SQLException {
    return delegate.enquoteNCharLiteral(val);
  }

  @Override
  public boolean equals(Object obj) {
    return this == obj;
  }

  @Override
  public int hashCode() {
    return System.identityHashCode(this);
  }

  @Override
  public String toString() {
    return "RecordingStatement[" + delegate + "]";
  }

  final void recordCall(@Nullable String effectiveSql) {
    String operation = firstSqlToken(effectiveSql);
    externalCallRecorder.record(ExternalCallRecorder.TYPE_DATABASE, target, operation,
            effectiveSql);
  }

  final void recordBatch() {
    externalCallRecorder.record(ExternalCallRecorder.TYPE_DATABASE, target, OPERATION_BATCH, sql);
  }

  final @Nullable String effectiveSql(@Nullable String argumentSql) {
    return sql != null ? sql : argumentSql;
  }

  final @Nullable String sql() {
    return sql;
  }

  private static @NonNull String firstSqlToken(@Nullable String sql) {
    if (sql == null) {
      return "UNKNOWN";
    }
    String trimmed = sql.trim();
    if (trimmed.isEmpty()) {
      return "UNKNOWN";
    }
    int idx = 0;
    while (idx < trimmed.length() && Character.isWhitespace(trimmed.charAt(idx))) {
      idx++;
    }
    int end = idx;
    while (end < trimmed.length() && !Character.isWhitespace(trimmed.charAt(end))) {
      end++;
    }
    return trimmed.substring(idx, end).toUpperCase();
  }
}
