plugins {
  id 'java-library'
}

dependencies {
  api project(":dsl-api")
  implementation libs.slf4j.api
  implementation libs.javaparser
  implementation libs.victools.jsonschema.generator
  implementation libs.victools.jsonschema.module.jackson
  implementation libs.jackson.databind
  testAnnotationProcessor libs.avaje.jsonb.generator
  annotationProcessor libs.avaje.jsonb.generator

  testImplementation platform(libs.junit.bom)
  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testRuntimeOnly libs.junit.platform.launcher
}
