plugins {
  id 'java'
  alias(libs.plugins.spring.dm)
  id 'cbs.nova.dsl' version '0.0.1-SNAPSHOT'
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
  }
}

dependencies {
  implementation project(':dsl-api')
  implementation project(':dsl')
  compileOnly project(':starter')
  implementation libs.temporal.sdk
  implementation libs.avaje.jsonb
  annotationProcessor libs.avaje.jsonb.generator

  dslCompiler project(':dsl-api')
  dslCompiler project(':dsl')
  dslCompiler project(':dsl-codegen')
  dslCompiler project(':starter')
  dslCompiler libs.avaje.jsonb.generator
}

dslCompile {
  dslPackage = 'cbs.nova.dslexamples'
  buildVersion = 'v1'
}

spotless {
  java {
    targetExclude 'src/dsl/**/*.java'
    targetExclude 'src/models/**/*.java'
    targetExclude 'build/generated/**/*.java'
  }
}

tasks.named('spotlessJava') {
  dependsOn 'compileDsl'
}
