plugins {
  id 'java'
  alias(libs.plugins.spring.dm)
  id 'cbs.nova.dsl' version '0.0.1-SNAPSHOT'
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
  }
}

sourceSets {
  dslModels {
    java {
      srcDirs = ['src/main/java']
    }
  }
}

dependencies {
  implementation project(':dsl-api')
  implementation project(':dsl')
  compileOnly project(':starter')
  implementation libs.temporal.sdk

  dslCompiler project(':dsl-api')
  dslCompiler project(':dsl')
  dslCompiler project(':dsl-codegen')
  dslCompiler project(':starter')
}

tasks.register('compileDslModels', JavaCompile) {
  source = sourceSets.dslModels.java
  classpath = sourceSets.main.compileClasspath
  destinationDirectory = layout.buildDirectory.dir('classes/dsl-models')
}

tasks.named('compileDsl', JavaExec) {
  dependsOn 'compileDslModels'
  classpath.from(tasks.compileDslModels.outputs.files)
  getOutputDir().set(layout.buildDirectory.dir('generated-dsl'))
}

dslCompile {
  sourceDir = layout.projectDirectory.dir('dsl')
}

tasks.named('compileJava', JavaCompile) {
  dependsOn 'compileDsl'
  source += fileTree(layout.buildDirectory.dir('generated-dsl')) { include '**/*.java' }
}

spotless {
  java {
    targetExclude 'dsl/**/*.java'
    targetExclude layout.buildDirectory.dir('generated-dsl').get().asFile
  }
}
