plugins {
  id 'java'
  id 'maven-publish'
  alias(libs.plugins.cbs.nova.dsl)
}

group = 'cbs.nova'
version = '0.0.1-SNAPSHOT'

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  implementation libs.cbs.nova.dsl.api
  implementation libs.cbs.nova.dsl.runtime
  implementation libs.temporal.sdk
  implementation libs.avaje.jsonb
  annotationProcessor libs.avaje.jsonb.generator

  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testRuntimeOnly libs.junit.platform.launcher
}

dslCompile {
  dslPackage = 'cbs.nova.app.dsl'
  runtimeModule = ''
  buildVersion = providers.exec {
    commandLine 'git', 'rev-parse', '--short', 'HEAD'
  }.standardOutput.asText.get().trim()
  logLevel = 'INFO'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

tasks.named('test') {
  useJUnitPlatform()
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
    }
  }
  repositories {
    mavenLocal()
  }
}

tasks.named('compileTestJava') {
  dependsOn 'copyGeneratedClasses'
}
