package cbs.dsl.api;

import cbs.dsl.api.DslComponent.DslComponentModel;

/**
 * Service Provider Interface for generated implementation registrations.
 *
 * <p>Implementations are generated by the annotation processor and loaded via
 * {@link java.util.ServiceLoader} at application startup to register DSL components without runtime
 * classpath scanning.
 *
 * <p>Each implementation should register its DSL definitions into the provided
 * {@link DefinitionRegistry}. The {@link DefinitionRegistry} interface is used instead of the concrete
 * {@link DefinitionRegistry} to avoid circular dependencies between modules.
 */
public interface DefinitionRegistryProvider {

  /**
   * Register DSL definitions into the provided registry, using the supplied resolver for
   * {@link DslComponentModel#SPRING} components.
   *
   * @param registry the writable registry to populate with DSL definitions
   * @param resolver the component resolver; may be {@code null}
   */
  void register(DefinitionRegistry registry, DslComponentResolver resolver);

}
