package cbs.dsl.api;

/**
 * Service Provider Interface for generated implementation registrations.
 *
 * <p>Implementations are generated by the annotation processor and loaded via
 * {@link java.util.ServiceLoader} at application startup to register DSL components without runtime
 * classpath scanning.
 *
 * <p>Each implementation should register its DSL definitions into the provided
 * {@link WritableRegistry}. The {@link WritableRegistry} interface is used instead of the concrete
 * {@link cbs.nova.registry.DslRegistry} to avoid circular dependencies between modules.
 */
public interface ImplRegistrationProvider {
  /**
   * Register DSL definitions into the provided registry.
   *
   * @param registry the writable registry to populate with DSL definitions
   */
  void register(WritableRegistry registry);

  /**
   * Register DSL definitions into the provided registry, using the supplied resolver for
   * {@link DslComponentModel#SPRING} components.
   *
   * <p>The default implementation delegates to {@link #register(WritableRegistry)} so existing
   * generated code remains compatible. New generated code overrides this method and passes the
   * resolver to wrapper constructors.
   *
   * @param registry the writable registry to populate with DSL definitions
   * @param resolver the component resolver; may be {@code null}
   */
  default void register(WritableRegistry registry, DslComponentResolver resolver) {
    register(registry);
  }
}
