package cbs.dsl.api;

/**
 * Service Provider Interface for generated implementation registrations.
 *
 * <p>Implementations are generated by the annotation processor and loaded via
 * {@link java.util.ServiceLoader} at application startup to register DSL components without runtime
 * classpath scanning.
 *
 * <p>Each implementation should register its DSL definitions into the provided
 * {@link WritableRegistry}. The {@link WritableRegistry} interface is used instead of the concrete
 * {@link cbs.dsl.impl.ImplRegistry} to avoid circular dependencies between modules.
 */
public interface ImplRegistrationProvider {
  /**
   * Register DSL definitions into the provided registry.
   *
   * @param registry the writable registry to populate with DSL definitions
   */
  void register(WritableRegistry registry);
}
