package cbs.dsl.api;

/**
 * Service Provider Interface for generated Temporal specification registrations.
 *
 * <p>Implementations are generated by the annotation processor and loaded via
 * {@link java.util.ServiceLoader} at application startup to register Temporal activities and
 * workflows without runtime classpath scanning.
 *
 * <p>Each implementation should register its generated activities and workflows into the provided
 * {@link SpecDefinitionRegistry}. The {@link DslComponentResolver} is passed so that {@code SPRING}
 * model components can be looked up from the Spring context.
 */
public interface SpecDefinitionRegistryProvider {

  /**
   * Register generated Temporal activities and workflows into the provided registry.
   *
   * @param registry the writable registry to populate
   * @param resolver the component resolver; may be {@code null}
   */
  void register(SpecDefinitionRegistry registry, DslComponentResolver resolver);
}
