import argparse
import json
import re
import urllib.error
import urllib.request
from pathlib import Path

from ..printer import Printer

DEFAULT_BASE_URL = "http://localhost:3000"
BFF_HELPERS_PATH = "/api/v1/dsl/helpers"
BACKEND_HELPERS_PATH = "/api/dsl/helpers"
BACKEND_OBJECTS_SEARCH_PATH = "/api/dsl/objects/search"
PAGE_SIZE = 100

# Only fields that exist on the backend HelperCatalogEntry
# (cbs/nova/starter/model/DslIntrospectionModels.java) are rendered.
ENTRY_FIELDS = ("name", "description", "inputType", "outputType")


def _cell(value) -> str:
    """Normalize a catalog cell: pipes/newlines escaped so the markdown table stays intact."""
    if value is None:
        return ""
    text = re.sub(r"\s+", " ", str(value)).strip()
    return text.replace("|", "\\|")


def normalize_entries(payload):
    """Extract helper entries from any known response envelope.

    Accepts:
      - a page envelope: {"items": [...], "total": n, "offset": n, "limit": n}
      - a catalog envelope: {"helpers": [...]} / {"entries": [...]}
      - a names envelope: {"names": ["a", ...]} (descriptions unavailable)
      - a bare JSON list of entry objects
    Each entry is reduced to the fields that exist on HelperCatalogEntry.
    """
    if isinstance(payload, list):
        items = payload
    elif isinstance(payload, dict):
        if isinstance(payload.get("items"), list):
            items = payload["items"]
        elif isinstance(payload.get("helpers"), list):
            items = payload["helpers"]
        elif isinstance(payload.get("entries"), list):
            items = payload["entries"]
        elif isinstance(payload.get("names"), list):
            items = [{"name": n} for n in payload["names"]]
        else:
            items = []
    else:
        items = []
    entries = []
    for item in items:
        if not isinstance(item, dict) or not item.get("name"):
            continue
        entries.append({field: item.get(field) for field in ENTRY_FIELDS})
    return entries


def render_helpers_md(entries) -> str:
    """Render the committed docs/helpers.md reference. Deterministic: sorted by name,
    no timestamps, helper count in the header."""
    rows = sorted(entries, key=lambda e: (str(e.get("name") or "").lower(), str(e.get("name") or "")))
    lines = [
        "# DSL Helpers Reference",
        "",
        "> Generated by `make helpers-doc` (needs the stack running) — do not edit by hand.",
        "> For how to author and call helpers from DSL code, see the",
        "> [helpers authoring guide](dsl/helpers.md).",
        "",
        f"{len(rows)} helpers, sorted by name.",
        "",
        "| Name | Description | Input | Output |",
        "|---|---|---|---|",
    ]
    for entry in rows:
        lines.append(
            "| {name} | {description} | {input_type} | {output_type} |".format(
                name=_cell(entry.get("name")),
                description=_cell(entry.get("description")),
                input_type=_cell(entry.get("inputType")),
                output_type=_cell(entry.get("outputType")),
            )
        )
    lines.append("")
    return "\n".join(lines)


def _get_json(url: str):
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as res:
        return json.loads(res.read().decode("utf-8"))


def _page_limit(payload) -> int:
    if isinstance(payload, dict) and isinstance(payload.get("limit"), int) and payload["limit"] > 0:
        return payload["limit"]
    return PAGE_SIZE


def _fetch_paginated(url: str, type_filter=None):
    """Fetch every page of a page-envelope endpoint ({items,total,offset,limit}).

    When type_filter is given, only items whose `type` field is in the set are kept
    (client-side filtering — the backend objects/search endpoint has no helper type
    filter since DslType has no HELPER constant).
    """
    all_entries = []
    page = 0
    sep = "&" if "?" in url else "?"
    while True:
        payload = _get_json(f"{url}{sep}page={page}&size={PAGE_SIZE}")
        if type_filter is not None and isinstance(payload, dict):
            raw_items = [i for i in payload.get("items", []) if isinstance(i, dict)]
            entries = normalize_entries([i for i in raw_items if i.get("type") in type_filter])
        else:
            entries = normalize_entries(payload)
        all_entries.extend(entries)
        if not isinstance(payload, dict):
            break
        total = payload.get("total")
        if isinstance(total, int):
            if len(all_entries) >= total:
                break
        elif len(entries) < _page_limit(payload):
            break
        if not entries:
            break
        page += 1
    return all_entries


def fetch_helpers(base_url: str, backend_mode: bool):
    """Fetch the full helper catalog, following pagination when the endpoint pages.

    Backend mode tries /api/dsl/helpers first and falls back to the paginated
    /api/dsl/objects/search endpoint, keeping only items whose type is "helper"
    or "function" (the backend objects/search endpoint has no helper type filter).
    """
    root = base_url.rstrip("/")
    if backend_mode:
        try:
            return _fetch_paginated(root + BACKEND_HELPERS_PATH)
        except urllib.error.HTTPError as e:
            if e.code != 404:
                raise
        Printer.warn(f"{BACKEND_HELPERS_PATH} not found; falling back to objects/search")
        return _fetch_paginated(root + BACKEND_OBJECTS_SEARCH_PATH, type_filter={"helper", "function"})
    return _fetch_paginated(root + BFF_HELPERS_PATH)


class HelpersDocCommand:
    def run(self, args: argparse.Namespace) -> int:
        out = Path(getattr(args, "out", None) or "docs/helpers.md")
        backend_url = getattr(args, "backend_url", None)
        base_url = backend_url or getattr(args, "base_url", None) or DEFAULT_BASE_URL
        backend_mode = bool(backend_url)

        Printer.header(f"Fetching helper catalog from {base_url}...")
        try:
            entries = fetch_helpers(base_url, backend_mode)
        except urllib.error.URLError as e:
            Printer.fail(f"fetch failed: {e}")
            return 1

        if not entries:
            Printer.fail("helper catalog is empty (is the stack running?)")
            return 1

        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render_helpers_md(entries), encoding="utf-8")
        Printer.ok(f"{len(entries)} helpers")
        Printer.ok(f"wrote {out}")
        return 0
