plugins {
  id 'java-library'
}

dependencies {
  implementation project(":dsl-api")
  implementation project(':dsl')
  implementation libs.slf4j.api
  runtimeOnly libs.slf4j.simple
  implementation libs.javaparser
  implementation libs.orgjson

  annotationProcessor libs.avaje.jsonb.generator
  runtimeOnly libs.avaje.jsonb.generator

  testImplementation platform(libs.junit.bom)
  testImplementation libs.junit.jupiter
  testImplementation libs.assertj
  testRuntimeOnly libs.junit.platform.launcher
}
