plugins {
  id 'java-library'
  id 'maven-publish'
  alias(libs.plugins.spring.boot)
  alias(libs.plugins.spring.dm)
}

bootJar {
  enabled = true
}

jar {
  enabled = true
}

springBoot {
  buildInfo()
}

dependencies {
  api project(":dsl-api")
  api project(':dsl')
  api project(':misc-codegen')

  api libs.avaje.jsonb
  annotationProcessor libs.avaje.jsonb.generator

  compileOnly libs.bundles.spring.web
  implementation libs.spring.boot.starter.actuator
  implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
  implementation 'org.flywaydb:flyway-core'
  implementation 'com.fasterxml.jackson.core:jackson-databind'
  runtimeOnly 'org.postgresql:postgresql'
  implementation libs.springdoc.openapi.starter.webmvc.ui
  compileOnly libs.openfeign.core
  compileOnly 'org.springframework.kafka:spring-kafka'

  api libs.temporal.sdk
  api libs.sentry.spring.boot.jakarta

  annotationProcessor project(':misc-codegen')

  testAnnotationProcessor project(':dsl-codegen')
  testImplementation project(':dsl-examples')

  testImplementation libs.springdoc.openapi.starter.webmvc.ui
  testImplementation libs.spring.boot.starter.actuator
  testImplementation libs.bundles.spring.web
  testImplementation libs.bundles.spring.test
  testImplementation libs.temporal.testing
  testImplementation libs.openfeign.core
  testImplementation libs.testcontainers.core
  testImplementation libs.testcontainers.junit.jupiter
  testImplementation libs.testcontainers.postgresql
  testImplementation libs.keycloak.admin.client
  testImplementation 'com.h2database:h2'
  testImplementation libs.rest.assured
  testImplementation libs.awaitility
  testImplementation libs.spring.jdbc
  testImplementation libs.wiremock
  testImplementation 'org.springframework.kafka:spring-kafka'
}

processIntegrationTestResources {
  duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
