package cbs.dsl.codegen;

import lombok.RequiredArgsConstructor;

import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@RequiredArgsConstructor
public class DefinitionRegistryGenerator {

  private final Filer filer;

  public void generate(List<RegistrationModel> registrations) throws IOException {
    generateImplRegistrations(registrations);
    generateSpiFile();
  }

  private void generateSpiFile() throws IOException {
    FileObject spiFile = filer.createResource(
        StandardLocation.CLASS_OUTPUT,
        "",
        "META-INF/services/cbs.dsl.api.DefinitionRegistryProvider");
    try (PrintWriter writer = new PrintWriter(spiFile.openWriter())) {
      writer.println(Substitutor.format(
          """
          # Generated by RegistrationGenerator
          # Date: {{date}}
          # Source: Java
          cbs.dsl.codegen.generated.DefinitionRegistryProviderImpl
          """, Map.of("date", DateTimeFormatter.ISO_INSTANT.format(Instant.now()))));
    }
  }

  private void generateImplRegistrations(List<RegistrationModel> registrations) throws IOException {
    JavaFileObject file =
        filer.createSourceFile("cbs.dsl.codegen.generated.DefinitionRegistryProviderImpl");

    String imports = registrations.stream()
        .map(spec -> Substitutor.format(
            "import cbs.dsl.codegen.generated.definitions.{{className}}Definition;",
            Map.of("className", spec.className())))
        .collect(Collectors.joining("\n"));

    String registrationsCode;
    if (registrations.isEmpty()) {
      registrationsCode = "        // No DSL components to register";
    } else {
      registrationsCode = registrations.stream()
          .map(spec -> Substitutor.format(
              "        registry.register(new {{className}}Definition(resolver));",
              Map.of("className", spec.className())))
          .collect(Collectors.joining("\n"));
    }

    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());
    String javaVersion = System.getProperty("java.version", "unknown");
    String generatorVersion = "1.0.0";

    String sourceTemplate = // language=java
        """
        package cbs.dsl.codegen.generated;

        import cbs.dsl.api.DefinitionRegistryProvider;import cbs.dsl.api.DslComponentResolver;
                import cbs.dsl.api.DefinitionRegistry;
        {{imports}}

        /**
         * Generated implementation registrant.
         * <p>
         * This class is automatically generated by the {@code RegistrationGenerator} annotation processor.
         * It registers all discovered DSL component implementations with the provided registry.
         * </p>
         * <strong>WARNING:</strong> This file is auto-generated and will be completely overwritten on subsequent builds.
         * DO NOT edit this file manually. Any manual modifications will be permanently lost.
         *
         * <p>Generation Information:
         * <ul>
         *   <li>Date: {{timestamp}}</li>
         *   <li>Generator: RegistrationGenerator v{{generatorVersion}}</li>
         *   <li>Source Language: Java</li>
         *   <li>Java Version: {{javaVersion}}</li>
         * </ul>
         * </p>
         *
         * @see DefinitionRegistryGenerator
         * @see DefinitionRegistryProvider
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.RegistrationGenerator",
            date = "{{timestamp}}",
            comments = "GeneratorVersion={{generatorVersion}}, Source=Java, JavaVersion={{javaVersion}}"
        )
        public class DefinitionRegistryProviderImpl implements DefinitionRegistryProvider {

            /**
             * Registers all generated DSL component implementations using the supplied resolver.
             *
             * @param registry the registry to register implementations with
             * @param resolver the component resolver; may be {@code null}
             */
            @Override
            public void register(DefinitionRegistry registry, DslComponentResolver resolver) {
              {{registrations}}
            }

        }
        """;

    String sourceCode = Substitutor.format(
        sourceTemplate,
        Map.ofEntries(
            Map.entry("imports", imports.isBlank() ? "" : "\n" + imports),
            Map.entry("timestamp", timestamp),
            Map.entry("generatorVersion", generatorVersion),
            Map.entry("javaVersion", javaVersion),
            Map.entry("registrations", registrationsCode)));

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(sourceCode);
    }
  }
}
