package cbs.dsl.codegen;

import cbs.dsl.api.DslObject;
import cbs.dsl.api.EventTypes.EventInput;
import cbs.dsl.api.EventTypes.EventOutput;
import cbs.dsl.api.MassOperationTypes.MassOperationInput;
import cbs.dsl.api.MassOperationTypes.MassOperationOutput;
import cbs.dsl.api.TransactionTypes.TransactionInput;
import cbs.dsl.api.TransactionTypes.TransactionOutput;
import cbs.dsl.api.TransitionRuleDefinition;
import cbs.dsl.api.WorkflowTypes.WorkflowInput;
import cbs.dsl.api.WorkflowTypes.WorkflowOutput;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Generates Java source files using JavaPoet.
 *
 * <p>Two generation modes are supported:
 *
 * <ol>
 *   <li>Wrapper classes for JEP 512 implicit-class DSL files.
 *   <li>Definition implementations from collected {@link DslObject} instances.
 * </ol>
 */
public final class DslCodeGenerator {

  private static final Pattern CLASS_NAME_PATTERN = Pattern.compile("public\\s+class\\s+(\\w+)");

  /**
   * Generates a wrapper class that embeds DSL body code inside a {@code main(String[])} method.
   *
   * @param className the desired class name
   * @param importBlock original import statements (preserved verbatim)
   * @param body the DSL body statements
   * @return the complete Java source including imports and wrapper class
   */
  public String generateWrapper(String className, String importBlock, String body) {
    MethodSpec mainMethod = MethodSpec.methodBuilder("main")
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(void.class)
        .addParameter(String[].class, "args")
        .addException(Exception.class)
        .addCode(body)
        .build();

    TypeSpec wrapperClass = TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addMethod(mainMethod)
        .build();

    JavaFile javaFile = JavaFile.builder("", wrapperClass).build();
    String generated = javaFile.toString();

    if (importBlock != null && !importBlock.isBlank()) {
      return importBlock.trim() + "\n\n" + generated;
    }
    return generated;
  }

  /**
   * Generates a Java source file from a {@link DslObject} and writes it to {@code outputDir}.
   *
   * @param object the DSL object collected during compilation
   * @param outputDir the directory where the {@code .java} file will be written
   * @throws IOException if writing the file fails
   */
  public void generate(DslObject object, Path outputDir) throws IOException {
    generate(object, null, null, outputDir);
  }

  public void generate(DslObject object, String dslBody, String dslImports, Path outputDir)
      throws IOException {
    TypeSpec typeSpec = buildTypeSpec(object, dslBody, dslImports);

    JavaFile javaFile = JavaFile.builder("cbs.dsl.generated", typeSpec)
        .addFileComment("Generated by DslCodeGenerator — do not edit")
        .build();

    String source = javaFile.toString();
    if (dslImports != null && !dslImports.isBlank()) {
      int packageEnd = source.indexOf("\n\n", source.indexOf("package "));
      if (packageEnd > 0) {
        source = source.substring(0, packageEnd + 2) + dslImports.trim() + "\n\n"
            + source.substring(packageEnd + 2);
      }
    }

    Matcher matcher = CLASS_NAME_PATTERN.matcher(source);
    String className = matcher.find() ? matcher.group(1) : "GeneratedClass";

    Path outputPath = outputDir.resolve("cbs/dsl/generated").resolve(className + ".java");
    Files.createDirectories(outputPath.getParent());
    Files.writeString(outputPath, source);
  }

  private TypeSpec buildTypeSpec(DslObject object, String dslBody, String dslImports) {
    Class<?> enclosing = object.getClass().getEnclosingClass();
    String typeName = enclosing != null ? enclosing.getSimpleName() : "";
    String simpleName = object.getClass().getSimpleName();

    return switch (typeName) {
      case "EventBuilder" -> buildEventTypeSpec(object, dslBody, dslImports);
      case "TransactionBuilder" -> buildTransactionTypeSpec(object, dslBody, dslImports);
      case "WorkflowBuilder" -> buildWorkflowTypeSpec(object, dslBody, dslImports);
      case "ConditionBuilder" -> buildConditionTypeSpec(object, dslBody, dslImports);
      case "HelperBuilder" -> buildHelperTypeSpec(object, dslBody, dslImports);
      case "MassOperationBuilder" -> buildMassOperationTypeSpec(object, dslBody, dslImports);
      default ->
        switch (simpleName) {
          case "EventDslObject" -> buildEventTypeSpec(object, dslBody, dslImports);
          case "TransactionDslObject" -> buildTransactionTypeSpec(object, dslBody, dslImports);
          case "WorkflowDslObject" -> buildWorkflowTypeSpec(object, dslBody, dslImports);
          case "ConditionDslObject" -> buildConditionTypeSpec(object, dslBody, dslImports);
          case "HelperDslObject" -> buildHelperTypeSpec(object, dslBody, dslImports);
          case "MassOperationDslObject" -> buildMassOperationTypeSpec(object, dslBody, dslImports);
          default ->
            throw new IllegalArgumentException(
                "Unsupported builder type: " + typeName + " / " + simpleName);
        };
    };
  }

  private TypeSpec buildEventTypeSpec(DslObject event, String dslBody, String dslImports) {
    String className = sanitizeClassName(event.getCode()) + "EventDefinition";
    String code = event.getCode();

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(EventOutput.class)
        .addParameter(EventInput.class, "input")
        .addStatement(
            "return new $T($T.emptyMap(), $S)", EventOutput.class, Collections.class, "SUCCESS")
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.event($S).build()", ClassName.get("cbs.dsl.builder", "EventDsl"), code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "EventDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(executeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private TypeSpec buildTransactionTypeSpec(DslObject tx, String dslBody, String dslImports) {
    String className = sanitizeClassName(tx.getCode()) + "TransactionDefinition";
    String code = tx.getCode();

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(TransactionOutput.class)
        .addParameter(TransactionInput.class, "input")
        .addStatement("return $T.empty()", TransactionOutput.class)
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.transaction($S).build()",
          ClassName.get("cbs.dsl.builder", "TransactionDsl"),
          code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "TransactionDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(executeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private TypeSpec buildWorkflowTypeSpec(DslObject wf, String dslBody, String dslImports) {
    String className = sanitizeClassName(wf.getCode()) + "WorkflowDefinition";
    String code = wf.getCode();
    List<String> states = invokeList(wf, "getStates");
    String initial = invokeString(wf, "getInitial");
    List<String> terminalStates = invokeList(wf, "getTerminalStates");

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec getStatesMethod = MethodSpec.methodBuilder("getStates")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(List.class, String.class))
        .addStatement("return $L", listOfLiterals(states))
        .build();

    MethodSpec getInitialMethod = MethodSpec.methodBuilder("getInitial")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", initial)
        .build();

    MethodSpec getTerminalStatesMethod = MethodSpec.methodBuilder("getTerminalStates")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(List.class, String.class))
        .addStatement("return $L", listOfLiterals(terminalStates))
        .build();

    MethodSpec getTransitionsMethod = MethodSpec.methodBuilder("getTransitions")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(List.class, TransitionRuleDefinition.class))
        .addStatement("return $T.emptyList()", Collections.class)
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(WorkflowOutput.class)
        .addParameter(WorkflowInput.class, "input")
        .addStatement("return new $T($S)", WorkflowOutput.class, "DONE")
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.workflow($S).build()", ClassName.get("cbs.dsl.builder", "WorkflowDsl"), code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "WorkflowDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(getStatesMethod)
        .addMethod(getInitialMethod)
        .addMethod(getTerminalStatesMethod)
        .addMethod(getTransitionsMethod)
        .addMethod(executeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private TypeSpec buildConditionTypeSpec(DslObject cond, String dslBody, String dslImports) {
    String className = sanitizeClassName(cond.getCode()) + "ConditionDefinition";
    String code = cond.getCode();

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.condition($S).build()",
          ClassName.get("cbs.dsl.builder", "ConditionDsl"),
          code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "ConditionDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private TypeSpec buildHelperTypeSpec(DslObject helper, String dslBody, String dslImports) {
    String className = sanitizeClassName(helper.getCode()) + "HelperDefinition";
    String code = helper.getCode();

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.helper($S).build()", ClassName.get("cbs.dsl.builder", "HelperDsl"), code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "HelperDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private TypeSpec buildMassOperationTypeSpec(DslObject mo, String dslBody, String dslImports) {
    String className = sanitizeClassName(mo.getCode()) + "MassOperationDefinition";
    String code = mo.getCode();

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", code)
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(MassOperationOutput.class)
        .addParameter(MassOperationInput.class, "input")
        .addStatement("return new $T(0L, 0L, $S)", MassOperationOutput.class, "SUCCESS")
        .build();

    MethodSpec.Builder dslMethodBuilder = MethodSpec.methodBuilder("dsl")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(DslObject.class);
    if (dslBody != null && !dslBody.isBlank()) {
      dslMethodBuilder.addCode(dslBody.trim() + "\n");
    } else {
      dslMethodBuilder.addStatement(
          "return $T.massOperation($S).build()",
          ClassName.get("cbs.dsl.builder", "MassOperationDsl"),
          code);
    }
    MethodSpec dslMethod = dslMethodBuilder.build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get("cbs.dsl.api", "MassOperationDefinition"))
        .addMethod(getCodeMethod)
        .addMethod(executeMethod)
        .addMethod(dslMethod)
        .build();
  }

  private static String listOfLiterals(List<String> items) {
    if (items == null || items.isEmpty()) {
      return "java.util.Collections.emptyList()";
    }
    return "java.util.List.of("
        + items.stream().map(s -> "\"" + s + "\"").collect(Collectors.joining(", "))
        + ")";
  }

  @SuppressWarnings("unchecked")
  private static List<String> invokeList(DslObject obj, String methodName) {
    try {
      Method method = obj.getClass().getDeclaredMethod(methodName);
      Object result = method.invoke(obj);
      if (result instanceof List<?> list) {
        return list.stream().map(Object::toString).collect(Collectors.toList());
      }
    } catch (Exception e) {
      // ignore
    }
    return Collections.emptyList();
  }

  private static String invokeString(DslObject obj, String methodName) {
    try {
      Method method = obj.getClass().getDeclaredMethod(methodName);
      Object result = method.invoke(obj);
      return result != null ? result.toString() : "";
    } catch (Exception e) {
      return "";
    }
  }

  private static String sanitizeClassName(String input) {
    String clean = input.replaceAll("[^a-zA-Z0-9_]", "_");
    if (clean.isEmpty()) {
      clean = "GeneratedClass";
    }
    return Character.toUpperCase(clean.charAt(0)) + clean.substring(1);
  }
}
