package cbs.dsl.codegen;

import cbs.dsl.api.ConditionDefinition;
import cbs.dsl.api.DslDefinition;
import cbs.dsl.api.EventDefinition;
import cbs.dsl.api.EventTypes.EventInput;
import cbs.dsl.api.EventTypes.EventOutput;
import cbs.dsl.api.HelperDefinition;
import cbs.dsl.api.TransactionDefinition;
import cbs.dsl.api.TransactionTypes.TransactionInput;
import cbs.dsl.api.TransactionTypes.TransactionOutput;
import cbs.dsl.api.TransitionRuleDefinition;
import cbs.dsl.api.WorkflowDefinition;
import cbs.dsl.api.WorkflowTypes.WorkflowInput;
import cbs.dsl.api.WorkflowTypes.WorkflowOutput;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;

import java.util.Collections;
import javax.lang.model.element.Modifier;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates Java source files using JavaPoet.
 *
 * <p>Two generation modes are supported:
 *
 * <ol>
 *   <li>Wrapper classes for JEP 512 implicit-class DSL files.
 *   <li>Definition implementations from collected {@link DslDefinition} objects.
 * </ol>
 */
public final class DslCodeGenerator {

  /**
   * Generates a wrapper class that embeds DSL body code inside a {@code main(String[])} method.
   *
   * @param className the desired class name
   * @param importBlock original import statements (preserved verbatim)
   * @param body the DSL body statements
   * @return the complete Java source including imports and wrapper class
   */
  public String generateWrapper(String className, String importBlock, String body) {
    MethodSpec mainMethod = MethodSpec.methodBuilder("main")
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(void.class)
        .addParameter(String[].class, "args")
        .addException(Exception.class)
        .addCode(body)
        .build();

    TypeSpec wrapperClass = TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addMethod(mainMethod)
        .build();

    JavaFile javaFile = JavaFile.builder("", wrapperClass).build();
    String generated = javaFile.toString();

    if (importBlock != null && !importBlock.isBlank()) {
      return importBlock.trim() + "\n\n" + generated;
    }
    return generated;
  }

  /**
   * Generates a Java source file from a {@link DslDefinition} and writes it to {@code outputDir}.
   *
   * @param definition the DSL definition collected during compilation
   * @param outputDir the directory where the {@code .java} file will be written
   * @throws IOException if writing the file fails
   */
  public void generate(DslDefinition definition, Path outputDir) throws IOException {
    TypeSpec typeSpec = buildTypeSpec(definition);

    JavaFile javaFile = JavaFile.builder("cbs.dsl.generated", typeSpec)
        .addFileComment("Generated by DslCodeGenerator — do not edit")
        .build();

    javaFile.writeTo(outputDir);
  }

  private TypeSpec buildTypeSpec(DslDefinition definition) {
    return switch (definition) {
      case EventDefinition event -> buildEventTypeSpec(event);
      case TransactionDefinition tx -> buildTransactionTypeSpec(tx);
      case WorkflowDefinition wf -> buildWorkflowTypeSpec(wf);
      case ConditionDefinition cond -> buildConditionTypeSpec(cond);
      case HelperDefinition helper -> buildHelperTypeSpec(helper);
      default ->
        throw new IllegalArgumentException("Unsupported definition type: " + definition.getClass());
    };
  }

  private TypeSpec buildEventTypeSpec(EventDefinition event) {
    String className = sanitizeClassName(event.getCode()) + "EventDefinition";

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", event.getCode())
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(EventOutput.class)
        .addParameter(EventInput.class, "input")
        .addStatement(
            "return new $T($T.emptyMap(), $S)",
            EventOutput.class,
            Collections.class,
            "SUCCESS")
        .build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(EventDefinition.class)
        .addMethod(getCodeMethod)
        .addMethod(executeMethod)
        .build();
  }

  private TypeSpec buildTransactionTypeSpec(TransactionDefinition tx) {
    String className = sanitizeClassName(tx.getCode()) + "TransactionDefinition";

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", tx.getCode())
        .build();

    MethodSpec previewMethod = MethodSpec.methodBuilder("preview")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(TransactionOutput.class)
        .addParameter(TransactionInput.class, "input")
        .addStatement("return execute(input)")
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(TransactionOutput.class)
        .addParameter(TransactionInput.class, "input")
        .addStatement(
            "return new $T($T.emptyMap(), $S)",
            TransactionOutput.class,
            Collections.class,
            "SUCCESS")
        .build();

    MethodSpec rollbackMethod = MethodSpec.methodBuilder("rollback")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(TransactionOutput.class)
        .addParameter(TransactionInput.class, "input")
        .addStatement(
            "return new $T($T.emptyMap(), $S)",
            TransactionOutput.class,
            Collections.class,
            "SUCCESS")
        .build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(TransactionDefinition.class)
        .addMethod(getCodeMethod)
        .addMethod(previewMethod)
        .addMethod(executeMethod)
        .addMethod(rollbackMethod)
        .build();
  }

  private TypeSpec buildWorkflowTypeSpec(WorkflowDefinition wf) {
    String className = sanitizeClassName(wf.getCode()) + "WorkflowDefinition";

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", wf.getCode())
        .build();

    MethodSpec getStatesMethod = MethodSpec.methodBuilder("getStates")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class)))
        .addStatement("return $L", listOfLiterals(wf.getStates()))
        .build();

    MethodSpec getInitialMethod = MethodSpec.methodBuilder("getInitial")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", wf.getInitial())
        .build();

    MethodSpec getTerminalStatesMethod = MethodSpec.methodBuilder("getTerminalStates")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class)))
        .addStatement("return $L", listOfLiterals(wf.getTerminalStates()))
        .build();

    MethodSpec getTransitionsMethod = MethodSpec.methodBuilder("getTransitions")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(
            ClassName.get(List.class),
            ClassName.get(TransitionRuleDefinition.class)))
        .addStatement("return $T.emptyList()", Collections.class)
        .build();

    MethodSpec executeMethod = MethodSpec.methodBuilder("execute")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(WorkflowOutput.class)
        .addParameter(WorkflowInput.class, "input")
        .addStatement("return new $T($S)", WorkflowOutput.class, "DONE")
        .build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(WorkflowDefinition.class)
        .addMethod(getCodeMethod)
        .addMethod(getStatesMethod)
        .addMethod(getInitialMethod)
        .addMethod(getTerminalStatesMethod)
        .addMethod(getTransitionsMethod)
        .addMethod(executeMethod)
        .build();
  }

  private TypeSpec buildConditionTypeSpec(ConditionDefinition cond) {
    String className = sanitizeClassName(cond.getCode()) + "ConditionDefinition";

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", cond.getCode())
        .build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ConditionDefinition.class)
        .addMethod(getCodeMethod)
        .build();
  }

  private TypeSpec buildHelperTypeSpec(HelperDefinition helper) {
    String className = sanitizeClassName(helper.getCode()) + "HelperDefinition";

    MethodSpec getCodeMethod = MethodSpec.methodBuilder("getCode")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(String.class)
        .addStatement("return $S", helper.getCode())
        .build();

    return TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(HelperDefinition.class)
        .addMethod(getCodeMethod)
        .build();
  }

  private static String listOfLiterals(List<String> items) {
    if (items == null || items.isEmpty()) {
      return "java.util.Collections.emptyList()";
    }
    return "java.util.List.of("
        + items.stream().map(s -> "\"" + s + "\"").collect(Collectors.joining(", "))
        + ")";
  }

  private static String sanitizeClassName(String input) {
    String clean = input.replaceAll("[^a-zA-Z0-9_]", "_");
    if (clean.isEmpty()) {
      clean = "GeneratedClass";
    }
    return Character.toUpperCase(clean.charAt(0)) + clean.substring(1);
  }
}
