package cbs.dsl.codegen;

import cbs.dsl.codegen.DslCompiler.FileWrite;

import javax.annotation.processing.Filer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EventSpecificationGenerator {

  private static final String GENERATED_PACKAGE = "cbs.dsl.codegen.generated";
  private static final String DEFINITIONS_PACKAGE = "cbs.dsl.codegen.generated.definitions";

  private final Filer filer;
  private final Path outputDir;

  public EventSpecificationGenerator() {
    this(null, null);
  }

  public EventSpecificationGenerator(Path outputDir) {
    this(null, outputDir);
  }

  public EventSpecificationGenerator(Filer filer) {
    this(filer, null);
  }

  private EventSpecificationGenerator(Filer filer, Path outputDir) {
    this.filer = filer;
    this.outputDir = outputDir;
  }

  public List<FileWrite> generate(List<EventSpecificationModel> specs) throws IOException {
    List<FileWrite> files = new ArrayList<>();
    for (EventSpecificationModel spec : specs) {
      files.addAll(generateFileSpecs(List.of(spec), outputDir));
    }
    return files;
  }

  public void generateAndWrite(List<EventSpecificationModel> specs) throws IOException {
    for (EventSpecificationModel spec : specs) {
      // Generate workflow interface and implementation (activity is generated by
      // EventDefinitionGenerator)
      String wfInterface = generateWorkflowInterfaceCode(spec);
      CodeGenUtil.writeToFiler(
          filer,
          GENERATED_PACKAGE + "." + CodeGenUtil.toClassName(spec.eventCode())
              + "EventSpecification",
          wfInterface);
      String wfImpl = generateWorkflowImplCode(spec);
      CodeGenUtil.writeToFiler(
          filer,
          DEFINITIONS_PACKAGE + "." + CodeGenUtil.toClassName(spec.eventCode())
              + "EventSpecificationImpl",
          wfImpl);
    }
  }

  public void write(List<FileWrite> files) throws IOException {
    for (FileWrite fw : files) {
      Files.createDirectories(fw.path().getParent());
      Files.writeString(fw.path(), fw.content());
    }
  }

  public List<FileWrite> generateFileSpecs(List<EventSpecificationModel> specs, Path outputDir) {
    List<FileWrite> files = new ArrayList<>();
    for (EventSpecificationModel spec : specs) {
      // Generate workflow interface and implementation (activity is generated by
      // EventDefinitionGenerator)
      files.add(new FileWrite(
          outputDir
              .resolve("cbs/dsl/codegen/generated")
              .resolve(CodeGenUtil.toClassName(spec.eventCode()) + "EventSpecification.java"),
          generateWorkflowInterfaceCode(spec)));
      files.add(new FileWrite(
          outputDir
              .resolve("cbs/dsl/codegen/generated")
              .resolve(CodeGenUtil.toClassName(spec.eventCode()) + "EventSpecificationImpl.java"),
          generateWorkflowImplCode(spec)));
    }
    return files;
  }

  public String generateWorkflowInterfaceCode(EventSpecificationModel spec) {
    String className = CodeGenUtil.toClassName(spec.eventCode()) + "EventSpecification";
    String timestamp = CodeGenUtil.currentTimestamp();

    String sourceTemplate = // language=java
        """
        package {{package}};
        
        import cbs.dsl.api.EventTypes.EventInput;
        import cbs.dsl.api.EventTypes.EventOutput;
        import cbs.dsl.api.EventOperation;
        import io.temporal.workflow.WorkflowInterface;
        import io.temporal.workflow.WorkflowMethod;
        import javax.annotation.processing.Generated;
        
        @Generated(
            value = "cbs.dsl.codegen.EventSpecificationGenerator",
            date = "{{timestamp}}"
        )
        @WorkflowInterface
        public interface {{className}} extends EventOperation {
        
            @Override
            @WorkflowMethod(name = "{{workflowMethodName}}")
            EventOutput execute(EventInput input)
        
        }
        """;

    return Substitutor.format(
        sourceTemplate,
        Map.of(
            "package", GENERATED_PACKAGE,
            "timestamp", timestamp,
            "className", className,
            "workflowMethodName", spec.eventCode()));
  }

  public String generateWorkflowImplCode(EventSpecificationModel spec) {
    String workflowClassName = CodeGenUtil.toClassName(spec.eventCode()) + "EventSpecification";
    String eventActivityClassName = CodeGenUtil.toClassName(spec.eventCode()) + "EventActivity";
    String eventActivityCode = spec.eventCode() + "_EVENT";
    String implClassName = workflowClassName + "Impl";
    String timestamp = CodeGenUtil.currentTimestamp();

    String sourceTemplate = // language=java
        """
        package {{package}};

        import cbs.dsl.api.EventTypes.EventInput;
        import cbs.dsl.api.EventTypes.EventOutput;
        import cbs.dsl.builder.EventDslObject;
        import cbs.dsl.evaluator.Evaluator;
        import cbs.nova.temporal.ActivityManager;
        import java.util.Map;
        import javax.annotation.processing.Generated;

        @Generated(
            value = "cbs.dsl.codegen.EventSpecificationGenerator",
            date = "{{timestamp}}"
        )
        public class {{implClassName}} implements {{workflowClassName}} {

            private final {{eventActivityClassName}} activity;
            private final Evaluator evaluator;
            //TODO: evaluate dsl on compilation phase and add transaction activities here

            public {{implClassName}}() {
                this.activity = ActivityManager.getInstance().newActivityStub(
                    "{{eventActivityCode}}", {{eventActivityClassName}}.class);
                this.evaluator = Evaluator.getInstance();
            }

            public String getCode() {
                return "{{eventCode}}";
            }

            @Override
            public EventOutput execute(EventInput input) {
                ContextOutput context = activity.prepare(input);
                var enrichedInput = input.toBuilder()
                  .params(context.params())
                  .build();
                EventContext eventContext = evaluator.evaluateEvent(dsl(), enrichedInput);

                return EventOutput.from(eventContext.params());
            }

            public EventDslObject dsl() {
                {{dslBody}}
            }

        }
        """;

    Map<String, String> params = new HashMap<>();
    params.put("package", DEFINITIONS_PACKAGE);
    params.put("timestamp", timestamp);
    params.put("implClassName", implClassName);
    params.put("workflowClassName", workflowClassName);
    params.put("eventActivityClassName", eventActivityClassName);
    params.put("eventActivityCode", eventActivityCode);
    params.put("eventCode", spec.eventCode());
    params.put("dslBody", spec.dslBody());
    return Substitutor.format(sourceTemplate, params);
  }
}
