package cbs.dsl.codegen;

import cbs.dsl.codegen.DslCompiler.FileWrite;

import javax.annotation.processing.Filer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class EventSpecificationGenerator  {

  private static final String GENERATED_PACKAGE = "cbs.dsl.codegen.generated";

  private final Filer filer;
  private final Path outputDir;

  public EventSpecificationGenerator() {
    this(null, null);
  }

  public EventSpecificationGenerator(Path outputDir) {
    this(null, outputDir);
  }

  public EventSpecificationGenerator(Filer filer) {
    this(filer, null);
  }

  private EventSpecificationGenerator(Filer filer, Path outputDir) {
    this.filer = filer;
    this.outputDir = outputDir;
  }

  public List<FileWrite> generate(List<EventWorkflowModel> specs) throws IOException {
    List<FileWrite> files = new ArrayList<>();
    for (EventWorkflowModel spec : specs) {
      files.addAll(generateFileSpecs(List.of(spec), outputDir));
    }
    return files;
  }

  public void generateAndWrite(List<EventWorkflowModel> specs) throws IOException {
    for (EventWorkflowModel spec : specs) {
      // Generate workflow interface and implementation (activity is generated by EventDefinitionGenerator)
      String wfInterface = generateWorkflowInterfaceCode(spec);
      CodeGenUtil.writeToFiler(
          filer,
          GENERATED_PACKAGE + "." + CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflow",
          wfInterface);
      String wfImpl = generateWorkflowImplCode(spec);
      CodeGenUtil.writeToFiler(
          filer,
          GENERATED_PACKAGE + "." + CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflowImpl",
          wfImpl);
    }
  }

  public void write(List<FileWrite> files) throws IOException {
    for (FileWrite fw : files) {
      Files.createDirectories(fw.path().getParent());
      Files.writeString(fw.path(), fw.content());
    }
  }

  public List<FileWrite> generateFileSpecs(List<EventWorkflowModel> specs, Path outputDir) {
    List<FileWrite> files = new ArrayList<>();
    for (EventWorkflowModel spec : specs) {
      // Generate workflow interface and implementation (activity is generated by EventDefinitionGenerator)
      files.add(new FileWrite(
          outputDir
              .resolve("cbs/dsl/codegen/generated")
              .resolve(CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflow.java"),
          generateWorkflowInterfaceCode(spec)));
      files.add(new FileWrite(
          outputDir
              .resolve("cbs/dsl/codegen/generated")
              .resolve(CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflowImpl.java"),
          generateWorkflowImplCode(spec)));
    }
    return files;
  }

  public String generateWorkflowInterfaceCode(EventWorkflowModel spec) {
    String className = CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflow";
    String timestamp = CodeGenUtil.currentTimestamp();

    String sourceTemplate = // language=java
        """
        package {{package}};

        import cbs.nova.model.EventWorkflowRequest;
        import cbs.nova.model.WorkflowExecutionResponse;
        import io.temporal.workflow.WorkflowInterface;
        import io.temporal.workflow.WorkflowMethod;
        import javax.annotation.processing.Generated;

        @Generated(
            value = "cbs.dsl.codegen.EventSpecificationGenerator",
            date = "{{timestamp}}"
        )
        @WorkflowInterface
        public interface {{className}} {

            @WorkflowMethod(name = "{{workflowMethodName}}")
            WorkflowExecutionResponse execute(EventWorkflowRequest input);
        }
        """;

    return Substitutor.format(
        sourceTemplate,
        Map.of(
            "package", GENERATED_PACKAGE,
            "timestamp", timestamp,
            "className", className,
            "workflowMethodName", spec.eventCode()));
  }

  public String generateWorkflowImplCode(EventWorkflowModel spec) {
    String workflowClassName = CodeGenUtil.toClassName(spec.eventCode()) + "EventWorkflow";
    String eventActivityClassName = CodeGenUtil.toClassName(spec.eventCode()) + "EventActivity";
    String eventActivityCode = spec.eventCode() + "_EVENT";
    String implClassName = workflowClassName + "Impl";
    String timestamp = CodeGenUtil.currentTimestamp();

    String txActivityFields = spec.transactionCodes().stream()
        .map(tx -> {
          String txActivityInterfaceName = CodeGenUtil.toClassName(tx) + "TransactionActivity";
          return Substitutor.format(
              """
                    private final {{txActivityInterfaceName}} {{txActivityFieldName}};""",
              Map.of(
                  "txActivityInterfaceName", txActivityInterfaceName,
                  "txActivityFieldName", CodeGenUtil.toFieldName(tx) + "Activity"));
        })
        .collect(Collectors.joining("\n"));

    String txActivityInitializers = spec.transactionCodes().stream()
        .map(tx -> {
          String txActivityInterfaceName = CodeGenUtil.toClassName(tx) + "TransactionActivity";
          String fieldName = CodeGenUtil.toFieldName(tx) + "Activity";
          return Substitutor.format(
              """
                    this.{{fieldName}} = ActivityManager.getInstance().newActivityStub(
                        "{{txCode}}", {{txActivityInterfaceName}}.class);""",
              Map.of(
                  "fieldName", fieldName,
                  "txCode", tx,
                  "txActivityInterfaceName", txActivityInterfaceName));
        })
        .collect(Collectors.joining("\n"));

    String txExecutionCalls = spec.transactionCodes().stream()
        .map(tx -> {
          String fieldName = CodeGenUtil.toFieldName(tx) + "Activity";
          return Substitutor.format(
              """
                    // Execute transaction {{txCode}}
                    TransactionInput {{fieldName}}Input = new TransactionInput(
                        context, input.eventCode());
                    {{fieldName}}.execute({{fieldName}}Input);""",
              Map.of(
                  "fieldName", fieldName,
                  "txCode", tx));
        })
        .collect(Collectors.joining("\n"));

    String sourceTemplate = // language=java
        """
        package {{package}};

        import cbs.dsl.api.TransactionTypes.TransactionInput;
        import cbs.nova.model.EventWorkflowRequest;
        import cbs.nova.model.WorkflowExecutionResponse;
        import cbs.nova.temporal.ActivityManager;
        import java.util.Map;
        import javax.annotation.processing.Generated;

        @Generated(
            value = "cbs.dsl.codegen.EventSpecificationGenerator",
            date = "{{timestamp}}"
        )
        public class {{implClassName}} implements {{workflowClassName}} {

            private static final ActivityManager activityManager = ActivityManager.getInstance();

            private final {{eventActivityClassName}} activity;
            {{txActivityFields}}

            public {{implClassName}}() {
                this.activity = activityManager.newActivityStub(
                    "{{eventActivityCode}}", {{eventActivityClassName}}.class);
                {{txActivityInitializers}}
            }

            @Override
            public WorkflowExecutionResponse execute(EventWorkflowRequest input) {
                // 1. Prepare context via event activity
                Map<String, Object> context = activity.prepareContext(input);

                // 2. Execute transactions sequentially
        {{txExecutionCalls}}

                return new WorkflowExecutionResponse(null, "COMPLETED");
            }
        }
        """;

    return Substitutor.format(
        sourceTemplate,
        Map.of(
            "package", GENERATED_PACKAGE,
            "timestamp", timestamp,
            "implClassName", implClassName,
            "workflowClassName", workflowClassName,
            "eventActivityClassName", eventActivityClassName,
            "eventActivityCode", eventActivityCode,
            "txActivityFields", txActivityFields,
            "txActivityInitializers", txActivityInitializers,
            "txExecutionCalls", txExecutionCalls));
  }
}
