package cbs.dsl.codegen;

import javax.annotation.processing.Filer;
import javax.tools.JavaFileObject;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates Temporal workflow interface + implementation for each {@code @DslComponent(type =
 * EVENT)}.
 *
 * <p>For each event, two classes are generated:
 *
 * <ol>
 *   <li>{@code {Code}Workflow} — a {@code @WorkflowInterface} with a unique {@code @WorkflowMethod}
 *       whose name is the event code (e.g. {@code "SAMPLE_EVENT"}).
 *   <li>{@code {Code}EventWorkflow} — the implementation that delegates execution to
 *       {@link cbs.nova.service.EventWorkflowOrchestrator}.
 * </ol>
 *
 * <p>The unique workflow method name allows {@code WorkflowExecutor} to start the correct workflow
 * via {@code WorkflowClient.newUntypedWorkflowStub(eventCode, options)}.
 */
public class EventWorkflowGenerator {

  private final Filer filer;

  public EventWorkflowGenerator(Filer filer) {
    this.filer = filer;
  }

  public void generate(List<EventWorkflowSpec> specs) throws IOException {
    for (EventWorkflowSpec spec : specs) {
      generateWorkflowInterface(spec);
      generateWorkflowImplementation(spec);
    }
  }

  private void generateWorkflowInterface(EventWorkflowSpec spec) throws IOException {
    String className = toClassName(spec.eventCode()) + "Workflow";
    String packageName = "cbs.dsl.codegen.generated";
    String fqcn = packageName + "." + className;

    JavaFileObject file = filer.createSourceFile(fqcn);
    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());

    String source =
        """
        package %s;

        import cbs.nova.model.EventWorkflowRequest;
        import cbs.nova.model.WorkflowExecutionResponse;
        import io.temporal.workflow.WorkflowInterface;
        import io.temporal.workflow.WorkflowMethod;

        /**
         * Generated Temporal workflow interface for event '%s'.
         *
         * <p><strong>WARNING:</strong> This file is auto-generated and will be completely overwritten
         * on subsequent builds. DO NOT edit this file manually.
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.EventWorkflowGenerator",
            date = "%s"
        )
        @WorkflowInterface
        public interface %s {

            @WorkflowMethod(name = "%s")
            WorkflowExecutionResponse execute(EventWorkflowRequest input);
        }
        """.formatted(packageName, spec.eventCode(), timestamp, className, spec.eventCode());

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(source);
    }
  }

  private void generateWorkflowImplementation(EventWorkflowSpec spec) throws IOException {
    String interfaceName = toClassName(spec.eventCode()) + "Workflow";
    String className = toClassName(spec.eventCode()) + "EventWorkflow";
    String packageName = "cbs.dsl.codegen.generated";
    String fqcn = packageName + "." + className;

    JavaFileObject file = filer.createSourceFile(fqcn);
    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());

    String txList = spec.transactionCodes().stream()
        .map(code -> "\"" + code + "\"")
        .collect(Collectors.joining(", "));

    String source = """
        package %s;

        import cbs.nova.model.EventWorkflowRequest;
        import cbs.nova.model.WorkflowExecutionResponse;
        import cbs.nova.service.EventWorkflowOrchestrator;
        import java.util.List;

        /**
         * Generated Temporal workflow implementation for event '%s'.
         *
         * <p><strong>WARNING:</strong> This file is auto-generated and will be completely overwritten
         * on subsequent builds. DO NOT edit this file manually.
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.EventWorkflowGenerator",
            date = "%s"
        )
        public class %s implements %s {

            private final EventWorkflowOrchestrator orchestrator;

            public %s(EventWorkflowOrchestrator orchestrator) {
                this.orchestrator = orchestrator;
            }

            @Override
            public WorkflowExecutionResponse execute(EventWorkflowRequest input) {
                return orchestrator.execute(input, List.of(%s));
            }
        }
        """.formatted(
            packageName, spec.eventCode(), timestamp, className, interfaceName, className, txList);

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(source);
    }
  }

  /** Converts an event code like "LOAN_SUBMIT" to a PascalCase class name prefix. */
  private static String toClassName(String code) {
    StringBuilder sb = new StringBuilder();
    boolean upper = true;
    for (char c : code.toCharArray()) {
      if (c == '_' || c == '-') {
        upper = true;
      } else if (upper) {
        sb.append(Character.toUpperCase(c));
        upper = false;
      } else {
        sb.append(Character.toLowerCase(c));
      }
    }
    return sb.toString();
  }
}
