package cbs.dsl.codegen;

import cbs.dsl.codegen.DslCompiler.FileWrite;

import javax.annotation.processing.Filer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Domain-oriented generator for {@code @DslComponent(type = EVENT)} components.
 *
 * <p>Produces activity-related artifacts per component:
 *
 * <ol>
 *   <li>{@code {Code}EventActivity} — Temporal {@code @ActivityInterface} with methods for context
 *       preparation and execution.
 *   <li>{@code {Code}Definition} — implements both {@code EventDefinition} and
 *       {@code {Code}EventActivity}. This hosts the DSL metadata, business delegation, and the
 *       Temporal activity contract.
 * </ol>
 *
 * <p>Note: Workflow artifacts ({@code {Code}Workflow} interface and {@code {Code}WorkflowImpl}) are
 * generated by {@link EventSpecificationGenerator} from DSL specifications.
 */
public class EventDefinitionGenerator implements DefinitionGenerator {

  private static final String EV_INPUT = "cbs.dsl.api.EventTypes.EventInput";
  private static final String EV_OUTPUT = "cbs.dsl.api.EventTypes.EventOutput";
  private static final String GENERATED_PACKAGE = "cbs.dsl.codegen.generated";
  private static final String DEFINITIONS_PACKAGE = "cbs.dsl.codegen.generated.definitions";

  private final Filer filer;
  private final Path outputDir;
  private final Function<RegistrationModel, String> dslBodyProvider;

  public EventDefinitionGenerator(Function<RegistrationModel, String> dslBodyProvider) {
    this(null, null, dslBodyProvider);
  }

  public EventDefinitionGenerator(
      Path outputDir, Function<RegistrationModel, String> dslBodyProvider) {
    this(null, outputDir, dslBodyProvider);
  }

  public EventDefinitionGenerator(
      Filer filer, Function<RegistrationModel, String> dslBodyProvider) {
    this(filer, null, dslBodyProvider);
  }

  private EventDefinitionGenerator(
      Filer filer, Path outputDir, Function<RegistrationModel, String> dslBodyProvider) {
    this.filer = filer;
    this.outputDir = outputDir;
    this.dslBodyProvider = dslBodyProvider;
  }

  @Override
  public List<FileWrite> generate(List<RegistrationModel> specs) throws IOException {
    if (outputDir != null) {
      List<FileWrite> files = new ArrayList<>();
      for (RegistrationModel spec : specs) {
        files.addAll(generateFileSpecs(spec, outputDir));
      }
      return files;
    }
    if (filer != null) {
      for (RegistrationModel spec : specs) {
        // Generate only Activity interface (workflow is generated by EventSpecificationGenerator)
        String activitySource = generateActivityInterfaceCode(spec);
        writeActivityInterface(spec, activitySource);
        String definitionSource = generateDefinitionCode(spec);
        writeDefinition(spec, definitionSource);
      }
    }
    return List.of();
  }

  @Override
  public void write(List<FileWrite> files) throws IOException {
    for (FileWrite fw : files) {
      Files.createDirectories(fw.path().getParent());
      Files.writeString(fw.path(), fw.content());
    }
  }

  public String generateActivityInterfaceCode(RegistrationModel spec) {
    String className = spec.className() + "EventActivity";
    String timestamp = CodeGenUtil.currentTimestamp();

    return Substitutor.format(
        // language=java
        """
        package {{package}};

        import cbs.dsl.api.EventTypes.EventInput;
        import cbs.dsl.api.EventTypes.EventOutput;
        import io.temporal.activity.ActivityInterface;
        import io.temporal.activity.ActivityMethod;
        import java.util.Map;
        import javax.annotation.processing.Generated;

        @Generated(
            value = "cbs.dsl.codegen.EventDefinitionGenerator",
            date = "{{timestamp}}"
        )
        @ActivityInterface
        public interface {{className}} {

            @ActivityMethod
            ContextOutput prepare(EventInput input);

            @ActivityMethod
            EventOutput execute(EventInput input);

        }
        """,
        Map.of(
            "package", GENERATED_PACKAGE,
            "timestamp", timestamp,
            "className", className));
  }

  public String generateDefinitionCode(RegistrationModel spec) {
    String wrapperClassName = spec.className() + "Definition";
    String activityInterfaceName = spec.className() + "EventActivity";

    String timestamp = CodeGenUtil.currentTimestamp();
    boolean inputIsRuntime = spec.inputType().equals(EV_INPUT);
    boolean outputIsRuntime = spec.outputType().equals(EV_OUTPUT);

    String jsonPayloadImport =
        (inputIsRuntime && outputIsRuntime) ? "" : "import cbs.dsl.api.JsonPayload;\n";
    String inputTypeImport = inputIsRuntime
        ? ""
        : Substitutor.format("import {{inputType}};\n", Map.of("inputType", spec.inputType()));
    String outputTypeImport = outputIsRuntime
        ? ""
        : Substitutor.format("import {{outputType}};\n", Map.of("outputType", spec.outputType()));

    String specImport = spec.packageName().isBlank()
        ? ""
        : "import " + spec.packageName() + "." + spec.className() + ";\n";

    String dslBody = dslBodyProvider.apply(spec);
    String dslImportsBlock = (spec.dslImports() != null && !spec.dslImports().isBlank())
        ? spec.dslImports().trim() + "\n"
        : "import cbs.dsl.builder.UndefinedDslObject;\n";

    String sourceTemplate = // language=java
        """
        package {{definitionsPackage}};

        import java.util.HashMap;
        import cbs.dsl.api.DslObject;
        import cbs.dsl.api.EventDefinition;
        import cbs.dsl.api.EventTypes.EventInput;
        import cbs.dsl.api.EventTypes.EventOutput;
        import cbs.dsl.api.ContextTypes.ContextOutput;
        import cbs.dsl.api.context.Context;
        import cbs.dsl.builder.EventDslObject;
        {{jsonPayloadImport}}        {{specImport}}{{inputTypeImport}}{{outputTypeImport}}
        {{dslImportsBlock}}        import java.util.Map;
        import javax.annotation.processing.Generated;

        /**
         * Generated EventDefinition wrapper + Activity implementation for {{specClassName}}.
         * <strong>WARNING:</strong> Auto-generated — do not edit.
         */
        @Generated(
            value = "cbs.dsl.codegen.EventDefinitionGenerator",
            date = "{{timestamp}}"
        )
        public class {{wrapperClassName}} implements EventDefinition, {{activityInterfaceName}} {

            private final Evaluator evaluator;

            public {{wrapperClassName}}(DslComponentResolver resolver) {
                this.evaluator = resolver.resolveEvaluator();
            }

            @Override
            public String getCode() {
                return "{{specCode}}";
            }
            
            //TODO: add method to filter input map from a `getParameters()`, like in `starter/src/main/java/cbs/nova/runner/EventRunner.java`

            @Override
            public ContextOutput prepare(EventInput input) {
                Context context = evaluator.evaluateContext(dsl(), input);
                return ContextOutput.from(context.params());
            }

            @Override
            public DslObject dsl() {
                {{dslBody}}
            }
        }
        """;

    Map<String, String> params = new HashMap<>();
    params.put("definitionsPackage", DEFINITIONS_PACKAGE);
    params.put("activityInterfaceName", activityInterfaceName);
    params.put("jsonPayloadImport", jsonPayloadImport);
    params.put("specImport", specImport);
    params.put("specClassName", spec.className());
    params.put("inputTypeImport", inputTypeImport);
    params.put("outputTypeImport", outputTypeImport);
    params.put("dslImportsBlock", dslImportsBlock);
    params.put("timestamp", timestamp);
    params.put("wrapperClassName", wrapperClassName);
    params.put("specCode", spec.code());
    params.put("inputSimpleName", CodeGenUtil.simpleName(spec.inputType()));
    params.put("outputSimpleName", CodeGenUtil.simpleName(spec.outputType()));
    params.put("dslBody", dslBody);
    return Substitutor.format(sourceTemplate, params);
  }

  public List<FileWrite> generateFileSpecs(RegistrationModel spec, Path outputDir) {
    List<FileWrite> files = new ArrayList<>();
    // Generate only Activity interface (workflow is generated by EventSpecificationGenerator)
    String activitySource = generateActivityInterfaceCode(spec);
    files.add(writeActivityInterfaceToSpec(spec, activitySource, outputDir));
    String definitionSource = generateDefinitionCode(spec);
    files.add(writeDefinitionToSpec(spec, definitionSource, outputDir));
    return files;
  }

  private FileWrite writeActivityInterfaceToSpec(
      RegistrationModel spec, String source, Path outputDir) {
    String className = spec.className() + "EventActivity";
    Path outputPath = outputDir.resolve("cbs/dsl/codegen/generated").resolve(className + ".java");
    return new FileWrite(outputPath, source);
  }

  private FileWrite writeDefinitionToSpec(RegistrationModel spec, String source, Path outputDir) {
    String wrapperClassName = spec.className() + "Definition";
    Path outputPath = outputDir
        .resolve("cbs/dsl/codegen/generated/definitions")
        .resolve(wrapperClassName + ".java");
    return new FileWrite(outputPath, source);
  }

  public void writeActivityInterface(RegistrationModel spec, String source) throws IOException {
    String className = spec.className() + "EventActivity";
    String fqcn = GENERATED_PACKAGE + "." + className;
    CodeGenUtil.writeToFiler(filer, fqcn, source);
  }

  public void writeDefinition(RegistrationModel spec, String source) throws IOException {
    String wrapperClassName = spec.className() + "Definition";
    String qualifiedName = DEFINITIONS_PACKAGE + "." + wrapperClassName;
    CodeGenUtil.writeToFiler(filer, qualifiedName, source);
  }
}
