package cbs.dsl.codegen;

import lombok.RequiredArgsConstructor;

import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

@RequiredArgsConstructor
public class RegistrationGenerator {

  private final Filer filer;

  public void generate(List<RegistrationSpec> registrations) throws IOException {
    generateImplRegistrations(registrations);
    generateSpiFile();
  }

  private void generateSpiFile() throws IOException {
    FileObject spiFile = filer.createResource(
        StandardLocation.CLASS_OUTPUT,
        "",
        "META-INF/services/cbs.dsl.api.ImplRegistrationProvider");
    try (PrintWriter writer = new PrintWriter(spiFile.openWriter())) {
      writer.println("""
          # Generated by RegistrationGenerator
          # Date: %s
          # Source: Java
          cbs.dsl.codegen.generated.GeneratedImplRegistrations
          """.formatted(DateTimeFormatter.ISO_INSTANT.format(Instant.now())));
    }
  }

  private void generateImplRegistrations(List<RegistrationSpec> registrations) throws IOException {
    JavaFileObject file =
        filer.createSourceFile("cbs.dsl.codegen.generated.GeneratedImplRegistrations");

    String imports = registrations.stream()
        .map(spec -> "import cbs.dsl.codegen.generated.definitions.%sDefinition;"
            .formatted(spec.className()))
        .collect(Collectors.joining("\n"));

    String registrationsCode;
    if (registrations.isEmpty()) {
      registrationsCode = "        // No DSL components to register";
    } else {
      registrationsCode = registrations.stream()
          .map(spec -> "        registry.register(new %sDefinition());".formatted(spec.className()))
          .collect(Collectors.joining("\n"));
    }

    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());
    String javaVersion = System.getProperty("java.version", "unknown");
    // TODO: redo with git.properties info
    String generatorVersion = "1.0.0";

    String sourceCode = """
        package cbs.dsl.codegen.generated;

        import cbs.dsl.api.ImplRegistrationProvider;
        import cbs.dsl.api.WritableRegistry;
        %s

        /**
         * Generated implementation registrant.
         * <p>
         * This class is automatically generated by the {@code RegistrationGenerator} annotation processor.
         * It registers all discovered DSL component implementations with the provided registry.
         * </p>
         * <strong>WARNING:</strong> This file is auto-generated and will be completely overwritten on subsequent builds.
         * DO NOT edit this file manually. Any manual modifications will be permanently lost.
         *
         * <p>Generation Information:
         * <ul>
         *   <li>Date: %s</li>
         *   <li>Generator: RegistrationGenerator v%s</li>
         *   <li>Source Language: Java</li>
         *   <li>Java Version: %s</li>
         * </ul>
         * </p>
         *
         * @see cbs.dsl.codegen.RegistrationGenerator
         * @see cbs.dsl.api.ImplRegistrationProvider
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.RegistrationGenerator",
            date = "%s",
            comments = "GeneratorVersion=%s, Source=Java, JavaVersion=%s"
        )
        public class GeneratedImplRegistrations implements ImplRegistrationProvider {

            /**
             * Registers all generated DSL component implementations.
             * <p>
             * This method is auto-generated and should not be modified manually.
             * </p>
             * @param registry the registry to register implementations with
             */
            @Override
            public void register(WritableRegistry registry) {
        %s
            }
        }
        """.formatted(
            imports.isBlank() ? "" : "\n" + imports,
            timestamp,
            generatorVersion,
            javaVersion,
            timestamp,
            generatorVersion,
            javaVersion,
            registrationsCode);

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(sourceCode);
    }
  }
}
