package cbs.dsl.codegen;

import javax.annotation.processing.Filer;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class RegistrationGenerator {

  private final Filer filer;

  public void generate(List<RegistrationSpec> registrations) throws IOException {
    generateImplRegistrations(registrations);
    generateSpiFile();
  }

  private void generateSpiFile() throws IOException {
    FileObject spiFile = filer.createResource(
        StandardLocation.CLASS_OUTPUT, "META-INF/services", "cbs.dsl.api.ImplRegistrationProvider");
    try (PrintWriter writer = new PrintWriter(spiFile.openWriter())) {
      writer.println("cbs.dsl.codegen.generated.GeneratedImplRegistrations");
    }
  }

  private void generateImplRegistrations(List<RegistrationSpec> registrations) throws IOException {
    JavaFileObject file =
        filer.createSourceFile("cbs.dsl.codegen.generated.GeneratedImplRegistrations");

    String imports = registrations.stream()
        .map(spec -> "import %s.%s;".formatted(spec.packageName(), spec.className()))
        .collect(Collectors.joining("\n"));

    String registrationsCode;
    if (registrations.isEmpty()) {
      registrationsCode = "        // No DSL components to register";
    } else {
      registrationsCode = registrations.stream()
          .map(spec -> "        registry.register(new %s());".formatted(spec.className()))
          .collect(Collectors.joining("\n"));
    }

    String sourceCode = """
        package cbs.dsl.codegen.generated;

        import cbs.dsl.api.ImplRegistrationProvider;
        import cbs.dsl.api.WritableRegistry;
        %s

        /**
         * Generated implementation registrant.
         * This file is auto-generated by the annotation processor.
         * Do not edit manually.
         */
        public class GeneratedImplRegistrations implements ImplRegistrationProvider {

            @Override
            public void register(WritableRegistry registry) {
        %s
            }
        }
        """.formatted(imports.isBlank() ? "" : "\n" + imports, registrationsCode);

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(sourceCode);
    }
  }
}