package cbs.dsl.codegen;

import lombok.RequiredArgsConstructor;

import javax.annotation.processing.Filer;
import javax.tools.JavaFileObject;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.MessageFormat;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a registry class that knows about all APT-generated event workflows.
 *
 * <p>The generated class provides a single {@code registerAll} method that registers every
 * generated workflow implementation with a Temporal {@link io.temporal.worker.Worker} using
 * {@code registerWorkflowImplementationFactory}. This eliminates reflection-based scanning at
 * runtime.
 */
@RequiredArgsConstructor
public class WorkflowRegistryGenerator {

  private final Filer filer;

  public void generate(List<EventWorkflowSpec> specs) throws IOException {
    if (specs.isEmpty()) {
      return;
    }

    String packageName = "cbs.dsl.codegen.generated";
    String className = "GeneratedWorkflowRegistry";
    String fqcn = packageName + "." + className;

    JavaFileObject file = filer.createSourceFile(fqcn);
    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());

    String interfaceImports = specs.stream()
        .map(s -> MessageFormat.format("import {0}.{1};", packageName, toInterfaceName(s.eventCode())))
        .collect(Collectors.joining("\n"));

    String implImports = specs.stream()
        .map(
            s -> MessageFormat.format("import {0}.definitions.{1};", packageName, toImplName(s.eventClassName())))
        .collect(Collectors.joining("\n"));

    String imports = interfaceImports + (implImports.isBlank() ? "" : "\n" + implImports);

    String factories = specs.stream()
        .map(s -> {
          String iface = toInterfaceName(s.eventCode());
          String impl = toImplName(s.eventClassName());
          String factoryTemplate = """
                  worker.registerWorkflowImplementationFactory(
                      {0}.class,
                      () -> new {1}(orchestrator));""";
          return MessageFormat.format(factoryTemplate, iface, impl);
        })
        .collect(Collectors.joining("\n\n"));

    String workflowTypes =
        specs.stream().map(s -> "\"" + s.eventCode() + "\"").collect(Collectors.joining(", "));

    String sourceTemplate = """
        package {0};

        import cbs.nova.service.EventWorkflowOrchestrator;
        import io.temporal.worker.Worker;
        import java.util.List;
        {1}

        /**
         * Generated registry for all APT-discovered event workflows.
         *
         * <p><strong>WARNING:</strong> This file is auto-generated and will be completely overwritten
         * on subsequent builds. DO NOT edit this file manually.
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.WorkflowRegistryGenerator",
            date = "{2}"
        )
        public final class {3} {

            private {3}() {}

            /**
             * Registers all generated workflow implementations with the given worker.
             *
             * @param worker the Temporal worker to register workflows on
             * @param orchestrator the orchestrator instance to inject into workflow implementations
             */
            public static void registerAll(Worker worker, EventWorkflowOrchestrator orchestrator) {
        {4}
            }

            /**
             * Returns the list of workflow type names generated by the annotation processor.
             *
             * @return list of event codes used as workflow type names
             */
            public static List<String> workflowTypes() {
                return List.of({5});
            }
        }
        """;

    String source = MessageFormat.format(sourceTemplate,
            packageName,
            imports.isBlank() ? "" : "\n" + imports,
            timestamp,
            className,
            className,
            factories,
            workflowTypes);

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(source);
    }
  }

  private static String toInterfaceName(String eventCode) {
    return toClassName(eventCode) + "Workflow";
  }

  private static String toImplName(String eventClassName) {
    int lastDot = eventClassName.lastIndexOf('.');
    String simpleName = lastDot >= 0 ? eventClassName.substring(lastDot + 1) : eventClassName;
    return simpleName + "Definition";
  }

  private static String toClassName(String code) {
    StringBuilder sb = new StringBuilder();
    boolean upper = true;
    for (char c : code.toCharArray()) {
      if (c == '_' || c == '-') {
        upper = true;
      } else if (upper) {
        sb.append(Character.toUpperCase(c));
        upper = false;
      } else {
        sb.append(Character.toLowerCase(c));
      }
    }
    return sb.toString();
  }
}