package cbs.dsl.codegen;

import javax.annotation.processing.Filer;
import javax.tools.JavaFileObject;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a registry class that knows about all APT-generated event workflows.
 *
 * <p>The generated class provides a single {@code registerAll} method that registers every
 * generated workflow implementation with a Temporal {@link io.temporal.worker.Worker} using
 * {@code registerWorkflowImplementationFactory}. This eliminates reflection-based scanning at
 * runtime.
 */
public class WorkflowRegistryGenerator {

  private final Filer filer;

  public WorkflowRegistryGenerator(Filer filer) {
    this.filer = filer;
  }

  public void generate(List<EventWorkflowSpec> specs) throws IOException {
    if (specs.isEmpty()) {
      return;
    }

    String packageName = "cbs.dsl.codegen.generated";
    String className = "GeneratedWorkflowRegistry";
    String fqcn = packageName + "." + className;

    JavaFileObject file = filer.createSourceFile(fqcn);
    String timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now());

    String imports = specs.stream()
        .map(s -> "import %s.%s;".formatted(packageName, toInterfaceName(s.eventCode())))
        .collect(Collectors.joining("\n"));

    String factories = specs.stream()
        .map(s -> {
          String iface = toInterfaceName(s.eventCode());
          String impl = toImplName(s.eventCode());
          return """
                  worker.registerWorkflowImplementationFactory(
                      %s.class,
                      () -> new %s(orchestrator));""".formatted(iface, impl);
        })
        .collect(Collectors.joining("\n\n"));

    String workflowTypes =
        specs.stream().map(s -> "\"" + s.eventCode() + "\"").collect(Collectors.joining(", "));

    String source = """
        package %s;

        import cbs.nova.service.EventWorkflowOrchestrator;
        import io.temporal.worker.Worker;
        import java.util.List;
        %s

        /**
         * Generated registry for all APT-discovered event workflows.
         *
         * <p><strong>WARNING:</strong> This file is auto-generated and will be completely overwritten
         * on subsequent builds. DO NOT edit this file manually.
         */
        @javax.annotation.processing.Generated(
            value = "cbs.dsl.codegen.WorkflowRegistryGenerator",
            date = "%s"
        )
        public final class %s {

            private %s() {}

            /**
             * Registers all generated workflow implementations with the given worker.
             *
             * @param worker the Temporal worker to register workflows on
             * @param orchestrator the orchestrator instance to inject into workflow implementations
             */
            public static void registerAll(Worker worker, EventWorkflowOrchestrator orchestrator) {
        %s
            }

            /**
             * Returns the list of workflow type names generated by the annotation processor.
             *
             * @return list of event codes used as workflow type names
             */
            public static List<String> workflowTypes() {
                return List.of(%s);
            }
        }
        """.formatted(
            packageName,
            imports.isBlank() ? "" : "\n" + imports,
            timestamp,
            className,
            className,
            factories,
            workflowTypes);

    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
      writer.print(source);
    }
  }

  private static String toInterfaceName(String eventCode) {
    return toClassName(eventCode) + "Workflow";
  }

  private static String toImplName(String eventCode) {
    return toClassName(eventCode) + "EventWorkflow";
  }

  private static String toClassName(String code) {
    StringBuilder sb = new StringBuilder();
    boolean upper = true;
    for (char c : code.toCharArray()) {
      if (c == '_' || c == '-') {
        upper = true;
      } else if (upper) {
        sb.append(Character.toUpperCase(c));
        upper = false;
      } else {
        sb.append(Character.toLowerCase(c));
      }
    }
    return sb.toString();
  }
}
