import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cbs_cli.commands.helpers_doc import normalize_entries, render_helpers_md  # noqa: E402


# ---------------------------------------------------------------------------
# normalize_entries — envelope handling
# ---------------------------------------------------------------------------

class TestNormalizeEntries:
    def test_page_envelope(self):
        payload = {
            "items": [
                {"name": "formatDate", "description": "Formats a date",
                 "inputType": "FormatDateIn", "outputType": "FormatDateOut", "type": "helper"},
            ],
            "total": 1,
            "offset": 0,
            "limit": 50,
        }
        entries = normalize_entries(payload)
        assert entries == [
            {"name": "formatDate", "description": "Formats a date",
             "inputType": "FormatDateIn", "outputType": "FormatDateOut"},
        ]

    def test_names_envelope(self):
        entries = normalize_entries({"names": ["alpha", "beta"]})
        assert entries == [
            {"name": "alpha", "description": None, "inputType": None, "outputType": None},
            {"name": "beta", "description": None, "inputType": None, "outputType": None},
        ]

    def test_bare_list(self):
        entries = normalize_entries([{"name": "x", "description": "d"}])
        assert len(entries) == 1
        assert entries[0]["name"] == "x"

    def test_stale_fields_dropped(self):
        """Fields removed from HelperCatalogEntry must not leak into the doc rows."""
        payload = {"items": [{
            "name": "httpCall", "description": None, "inputType": None, "outputType": None,
            "hasSideEffects": True, "previewBehavior": "fake",
        }]}
        entries = normalize_entries(payload)
        assert entries == [
            {"name": "httpCall", "description": None, "inputType": None, "outputType": None},
        ]

    def test_entries_without_name_skipped(self):
        entries = normalize_entries({"items": [{"description": "no name"}, {"name": "ok"}]})
        assert [e["name"] for e in entries] == ["ok"]


# ---------------------------------------------------------------------------
# render_helpers_md — deterministic markdown
# ---------------------------------------------------------------------------

def _entries():
    return [
        {"name": "formatDate", "description": "Formats a date string with a pattern",
         "inputType": "FormatDateIn", "outputType": "FormatDateOut"},
        {"name": "currentTimestamp", "description": "Returns the current ISO timestamp",
         "inputType": "void", "outputType": "string"},
        {"name": "httpCall", "description": None, "inputType": None, "outputType": None},
    ]


class TestRenderHelpersMd:
    def test_header_notes_generation_and_count(self):
        md = render_helpers_md(_entries())
        first_line = md.splitlines()[0]
        assert first_line == "# DSL Helpers Reference"
        assert "Generated by `make helpers-doc`" in md
        assert "do not edit by hand" in md
        assert "dsl/helpers.md" in md
        assert "3 helpers" in md

    def test_rows_sorted_by_name(self):
        md = render_helpers_md(_entries())
        lines = md.splitlines()
        names = [l.split("|")[1].strip() for l in lines[10:] if l.startswith("|")]
        assert names == ["currentTimestamp", "formatDate", "httpCall"]

    def test_expected_row_content(self):
        md = render_helpers_md(_entries())
        assert "| currentTimestamp | Returns the current ISO timestamp | void | string |" in md
        assert "| httpCall |  |  |  |" in md

    def test_deterministic_and_no_timestamps(self):
        md1 = render_helpers_md(_entries())
        md2 = render_helpers_md(list(reversed(_entries())))
        assert md1 == md2
        assert "20" not in md1.splitlines()[5]  # count line carries no date

    def test_pipe_and_newlines_escaped(self):
        entries = [{"name": "weird", "description": "a|b\nc", "inputType": None, "outputType": None}]
        md = render_helpers_md(entries)
        assert "a\\|b c" in md

    def test_table_shape(self):
        md = render_helpers_md(_entries())
        lines = md.splitlines()
        assert lines[8] == "| Name | Description | Input | Output |"
        assert lines[9] == "|---|---|---|---|"
        assert md.endswith("\n") and not md.endswith("\n\n")
