package cbs.dsl.codegen;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import cbs.dsl.api.DslComponent.DslComponentModel;
import cbs.dsl.codegen.DslCompiler.FileWrite;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

class EventDefinitionGeneratorTest {

  private static final String EV_INPUT = "cbs.dsl.api.EventTypes.EventInput";
  private static final String EV_OUTPUT = "cbs.dsl.api.EventTypes.EventOutput";

  @TempDir
  Path tempDir;

  @Test
  @DisplayName("shouldGenerateActivityInterfaceAndDefinitionWithUndefinedDsl")
  void shouldGenerateActivityInterfaceAndDefinitionWithUndefinedDsl()
      throws Exception {
    RegistrationModel spec = new RegistrationModel(
        "com.example",
        "MyEvent",
        "EVT_1",
        DslInterfaceType.EVENT,
        EV_INPUT,
        EV_OUTPUT,
        DslComponentModel.SIMPLE,
        null,
        null);

    EventDefinitionGenerator gen =
        new EventDefinitionGenerator(tempDir, s -> "return UndefinedDslObject.create();");
    List<FileWrite> files = gen.generate(List.of(spec));
    gen.write(files);

    // Workflow is generated by EventSpecificationGenerator, not EventDefinitionGenerator
    Path workflowPath = tempDir.resolve("cbs/dsl/codegen/generated/MyEventWorkflow.java");
    Path activityPath = tempDir.resolve("cbs/dsl/codegen/generated/MyEventEventActivity.java");
    Path definitionPath =
        tempDir.resolve("cbs/dsl/codegen/generated/definitions/MyEventDefinition.java");

    assertFalse(Files.exists(workflowPath),
        "Workflow should be generated by EventSpecificationGenerator, not EventDefinitionGenerator");
    assertTrue(Files.exists(activityPath), "Should generate MyEventEventActivity");
    assertTrue(Files.exists(definitionPath), "Should generate MyEventDefinition");

    // Verify activity interface content
    String activityContent = Files.readString(activityPath);
    assertNotNull(activityContent);
    assertTrue(activityContent.contains("@ActivityInterface"), "Should have @ActivityInterface");
    assertTrue(activityContent.contains("prepareContext"),
        "Should have prepareContext method");

    String content = Files.readString(definitionPath);
    assertNotNull(content);

    assertTrue(content.contains("class MyEventDefinition"), "Should contain class name");
    // Activity interface only - workflow interface is generated by EventSpecificationGenerator
    assertTrue(
        content.contains("implements EventDefinition, MyEventEventActivity"),
        "Should implement EventDefinition and Activity interface only");
    assertTrue(
        content.contains("return UndefinedDslObject.create();"),
        "Should contain UndefinedDslObject dsl body");
    assertTrue(
        content.contains("import cbs.dsl.builder.UndefinedDslObject;"),
        "Should contain UndefinedDslObject import");
  }

  @Test
  @DisplayName("shouldEmbedCustomDslBodyAndImportsWhenProvided")
  void shouldEmbedCustomDslBodyAndImportsWhenProvided() throws Exception {
    RegistrationModel spec = new RegistrationModel(
        "com.example",
        "MyEvent",
        "EVT_1",
        DslInterfaceType.EVENT,
        EV_INPUT,
        EV_OUTPUT,
        DslComponentModel.SIMPLE,
        "return CustomEventDsl.event(\"EVT_1\").build();",
        "import com.example.CustomEventDsl;");

    EventDefinitionGenerator gen = new EventDefinitionGenerator(tempDir, s -> s.dslBody());
    List<FileWrite> files = gen.generate(List.of(spec));
    gen.write(files);

    Path definitionPath =
        tempDir.resolve("cbs/dsl/codegen/generated/definitions/MyEventDefinition.java");
    assertTrue(Files.exists(definitionPath), "Should generate MyEventDefinition");
    String content = Files.readString(definitionPath);
    assertNotNull(content);

    assertTrue(
        content.contains("return CustomEventDsl.event(\"EVT_1\").build();"),
        "Should contain custom dsl body");
    assertTrue(
        content.contains("import com.example.CustomEventDsl;"), "Should contain custom dsl import");
    assertFalse(
        content.contains("import cbs.dsl.builder.UndefinedDslObject;"),
        "Should not contain UndefinedDslObject fallback import");
  }
}
